#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_content.py — generate every exercise's Scratch files + the web manifest.

For each exercise:
  • Mini Project / Home Task -> a STARTER (sprites placed, no code) in starters/
    and a FINISHED playable "desired output" in finished/.
  • Recall Test -> a playable quiz in starters/ (there is no separate desired
    output; the student takes the quiz).

Also writes assets/js/exercises.js (window.GN_COURSE) for the browser + player.

Run: python3 tools/build_content.py
"""
import os, sys, json, copy
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import templates
from curriculum import SESSIONS
from game_engine import Factory, whenflag, sayfor, _patch_menus, fix_parents, write_project

STARTERS = os.path.join(ROOT, "starters")
FINISHED = os.path.join(ROOT, "finished")
os.makedirs(STARTERS, exist_ok=True)
os.makedirs(FINISHED, exist_ok=True)

STARTER_TASK = {
 "collect": "Move with the arrow keys — collect all 3 and reach the goal!",
 "catch":   "Move the catcher with your mouse — catch the falling items!",
 "dodge":   "Move with the arrow keys — dodge every hazard!",
 "clicker": "Click me as fast as you can — reach the target score!",
 "flappy":  "Press Space to flap — fly through the gaps!",
 "whack":   "Click the target fast — before the timer runs out!",
 "pong":    "Move the paddle with your mouse — keep the ball up!",
 "runner":  "Press Space to jump over the obstacles!",
 "shooter": "Arrow keys to move, Space to shoot the enemies!",
 "drive":   "Arrow keys to drive — reach the finish flag!",
}


def sprites_of(template, theme):
    if template == "collect": return [theme["player"], theme["collectible"], theme["enemy"], theme["goal"]]
    if template == "catch":   return [theme["player"], theme["item"]]
    if template == "dodge":   return [theme["player"], theme["enemy"]]
    if template == "clicker": return [theme["target"]]
    if template == "flappy":  return [theme["player"], theme["obstacle"]]
    if template == "whack":   return [theme["target"]]
    if template == "pong":    return [theme["paddle"], theme["ball"]]
    if template == "runner":  return [theme["player"], theme["obstacle"]]
    if template == "shooter": return [theme["player"], theme["bullet"], theme["enemy"]]
    if template == "drive":   return [theme["player"], theme["goal"], theme["enemy"]]
    if template == "quiz":    return [theme.get("host", "Gobo")]
    return []


def make_starter(finished_targets, task):
    st = copy.deepcopy(finished_targets)
    for t in st:
        if not t["isStage"]:
            t["blocks"] = {}
    f = Factory("s")
    f.stack([whenflag(), sayfor(task, 4)])
    _patch_menus(f); fix_parents(f.blocks)
    st[-1]["blocks"] = f.blocks           # player is the last target in every template
    return st


def build():
    manifest_ex = {}
    sessions_out = []
    for s in SESSIONS:
        ex_ids = []
        for ex in s["exercises"]:
            xid = ex["id"]; tmpl = ex["template"]; theme = ex["theme"]
            targets, monitors = templates.TEMPLATES[tmpl](theme)
            if tmpl == "quiz":
                # the quiz itself is what the student plays; no separate desired output
                write_project(targets, monitors, os.path.join(STARTERS, xid + ".sb3"),
                              agent="GradeNext recall quiz")
                desired = None
            else:
                write_project(targets, monitors, os.path.join(FINISHED, xid + ".sb3"),
                              agent="GradeNext desired-output (%s)" % tmpl)
                starter = make_starter(targets, STARTER_TASK[tmpl])
                write_project(starter, [], os.path.join(STARTERS, xid + ".sb3"),
                              agent="GradeNext starter (%s)" % tmpl)
                desired = "finished/%s.sb3" % xid
            manifest_ex[xid] = {
                "id": xid, "session": s["id"], "sessionTitle": s["title"],
                "title": ex["title"], "type": ex["type"], "level": ex["level"],
                "tag": ex["tag"], "emoji": ex["emoji"], "color": ex["color"],
                "starter": "starters/%s.sb3" % xid, "desired": desired,
                "sprites": sprites_of(tmpl, theme), "backdrop": theme.get("backdrop", ""),
                "story": ex["story"], "hints": ex["hints"],
            }
            ex_ids.append(xid)
        sessions_out.append({"id": s["id"], "n": s["n"], "title": s["title"],
                             "emoji": s["emoji"], "color": s["color"],
                             "concept": s["concept"], "exercises": ex_ids})

    course = {"sessions": sessions_out, "exercises": manifest_ex}
    js = ("/* AUTO-GENERATED by tools/build_content.py — do not edit by hand. */\n"
          "window.GN_COURSE = " + json.dumps(course, separators=(",", ":")) + ";\n")
    open(os.path.join(ROOT, "assets", "js", "exercises.js"), "w", encoding="utf-8").write(js)
    open(os.path.join(ROOT, "starters", "course.json"), "w", encoding="utf-8").write(json.dumps(course, indent=1))

    n_ex = len(manifest_ex)
    n_fin = sum(1 for e in manifest_ex.values() if e["desired"])
    print("Built %d exercises across %d sessions (%d finished 'desired output' games, %d quizzes)."
          % (n_ex, len(sessions_out), n_fin, n_ex - n_fin))
    print("Wrote assets/js/exercises.js")


if __name__ == "__main__":
    build()
