#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
concepts.py — the TEACHING KNOWLEDGE BASE.

This is the part a content library cannot copy: for every Scratch concept we
teach, this file holds what a tutor actually needs in the room —

  strand      which Scratch block family it belongs to
  blocks      the exact blocks introduced
  vocab       kid-friendly definitions the tutor should use
  objectives  "I can ..." statements (what success looks like)
  hook        a 60-second warm-up that creates curiosity
  teach       the tutor's live teaching script, step by step
  watch       the mistakes children actually make, and the fix
  ask         check-for-understanding questions (with answers)
  support     what to do when a child is stuck
  stretch     what to do when a child finishes early
  rubric      emerging / secure / mastered descriptors for assessment

Everything downstream (lesson plans, report cards, mastery maps) is generated
from this file, so improving teaching quality means editing here.
"""

# Scratch block families, used for the skills/mastery map.
STRANDS = {
    "Basics":    "#64748b",
    "Motion":    "#4c97ff",
    "Looks":     "#9966ff",
    "Sound":     "#cf63cf",
    "Events":    "#ffbf00",
    "Control":   "#ffab19",
    "Sensing":   "#5cb1d6",
    "Operators": "#59c059",
    "Variables": "#ff8c1a",
    "MyBlocks":  "#ff6680",
    "Pen":       "#0fbd8c",
    "Design":    "#ff661a",
}


def C(name, strand, blocks, vocab, objectives, hook, teach, watch, ask,
      support, stretch, rubric):
    return {"name": name, "strand": strand, "blocks": blocks, "vocab": vocab,
            "objectives": objectives, "hook": hook, "teach": teach,
            "watch": watch, "ask": ask, "support": support, "stretch": stretch,
            "rubric": {"emerging": rubric[0], "secure": rubric[1], "mastered": rubric[2]}}


CONCEPTS = {}

# =====================================================================
# LEVEL 1 — Foundations
# =====================================================================

CONCEPTS["tour"] = C(
    "Meet Scratch", "Basics",
    ["when green flag clicked"],
    ["Sprite — a character or object you can give code to.",
     "Stage — the screen where your project happens.",
     "Script — a stack of blocks joined together.",
     "Palette — the coloured menu where blocks live."],
    ["I can name the stage, the sprite list and the block palette.",
     "I can drag a block into the code area and run it.",
     "I can start a project with the green flag."],
    "Show the child a finished game for 30 seconds and say: \"By the end of today YOU will have made something that runs like this. Ready?\"",
    ["Share your screen with a brand-new Scratch project. Point at three places only: the Stage (top right), the Sprite list (under it), the Block palette (left). Name each one and have the child repeat it back.",
     "Drag a `move 10 steps` block into the code area and click it. Say: \"Blocks do nothing until something runs them — clicking is one way.\"",
     "Snap `when green flag clicked` on top and run it with the flag. Say: \"Now the flag runs it. This is how every project starts.\"",
     "Hand over: ask the child to share their screen and do the same three steps themselves."],
    ["Child clicks the flag but nothing happens → the script has no hat block; check `when green flag clicked` is on top.",
     "Blocks are dropped near each other but not snapped → zoom in and show the white snap line as blocks join.",
     "Child edits the Stage instead of the sprite → point out the highlighted sprite thumbnail."],
    ["Where does a sprite's code live? → In the code area, when that sprite is selected.",
     "What does the green flag do? → Runs every `when green flag clicked` script.",
     "What is a sprite? → A character or object you can program."],
    "Do it hand-over-hand: you drag, they click run. Reduce to one block and one goal — make the cat move.",
    "Ask them to add a second block so the cat moves AND turns, then predict what will happen before running it.",
    ("Needs help to find the palette and drag a block.",
     "Drags, snaps and runs a two-block script independently.",
     "Explains stage/sprite/script in their own words and helps someone else find them."))

CONCEPTS["sequence"] = C(
    "Sequences: order matters", "Basics",
    ["move", "turn", "wait"],
    ["Sequence — instructions carried out in order, one after another.",
     "Algorithm — a set of steps to get something done."],
    ["I can predict what a stack of blocks will do before running it.",
     "I can put blocks in the right order to get the result I want.",
     "I can explain why changing the order changes the result."],
    "Give the tutor-as-robot game: the child instructs you to pick up a pen. Follow their words *exactly* and wrongly. They learn order and precision in 60 seconds.",
    ["Build a 3-block script (move, turn, move) and ask the child to PREDICT the path before you run it. Prediction first, always.",
     "Run it. Compare with their prediction. Celebrate the mismatch — that is learning.",
     "Now swap two blocks and ask again: same blocks, different order — will it look the same? Run it.",
     "Give them a target: 'make the sprite draw a square path'. Let them sequence it themselves."],
    ["Child assumes all blocks run at once → add `wait 1 seconds` between blocks so they SEE the order.",
     "Child expects the sprite to reset between runs → point out the sprite keeps its last position; add a `go to x y` at the start.",
     "Blocks in a stack but the child changes the wrong number → have them read the block aloud before editing."],
    ["If I swap these two blocks, will the result change? → Yes, order changes the outcome.",
     "What is an algorithm? → A set of steps in order to do a job.",
     "Why did the sprite end up somewhere different? → Because the steps ran in a different order."],
    "Use only two blocks and physical acting-out — walk the steps on the floor before coding them.",
    "Challenge: reach the same end point using a different order of blocks. Is more than one algorithm possible?",
    ("Places blocks with trial and error only.",
     "Predicts and orders a short sequence correctly.",
     "Explains that different orders give different results and finds two algorithms for one goal."))

CONCEPTS["motion-steps"] = C(
    "Move and turn", "Motion",
    ["move () steps", "turn right () degrees", "turn left () degrees", "point in direction ()"],
    ["Steps — how far a sprite moves (about one dot on the screen).",
     "Degrees — how much a sprite turns. 90 is a quarter turn."],
    ["I can move a sprite a chosen distance.",
     "I can turn a sprite by a chosen angle.",
     "I can combine moves and turns to follow a path."],
    "Stand up and be the sprite: 'move 10 steps' (take a step), 'turn 90 degrees' (quarter turn). Do it with your body before the screen.",
    ["Demo `move 10 steps` then change 10 to 100. Ask: what changed? Establish that the NUMBER is a control the child owns.",
     "Demo `turn 90 degrees`. Link to real turns: 90 = quarter, 180 = half, 360 = all the way round.",
     "Build move-turn-move-turn and run it four times to trace a square. Ask them to notice the repetition (this seeds loops next session).",
     "Set the task: get the sprite from one corner to a target using only moves and turns."],
    ["Sprite drifts off-screen and disappears → drag it back, or add `go to x: 0 y: 0` at the start.",
     "Sprite ends up upside-down → the rotation style; show 'left-right' in the sprite's Direction setting.",
     "Child types 90 in the move block expecting a turn → read blocks aloud to separate 'move' from 'turn'."],
    ["How many degrees is a quarter turn? → 90.",
     "What happens if I change 10 steps to 100? → It moves ten times further.",
     "How do I make the sprite go back the other way? → Turn 180, or move -10 steps."],
    "Pre-place the blocks and let the child only change the numbers, predicting each time.",
    "Ask for a triangle path — they must work out the turn is 120 degrees, not 90.",
    ("Moves a sprite with help; numbers changed at random.",
     "Chooses sensible step and degree values to reach a target.",
     "Reasons about angles (square 90, triangle 120) and plans a path before coding."))

CONCEPTS["looks-say"] = C(
    "Say, think and talk", "Looks",
    ["say () for () seconds", "say ()", "think () for () seconds"],
    ["Speech bubble — the little cloud showing what a sprite says.",
     "Duration — how long something stays on screen."],
    ["I can make a sprite speak for a set time.",
     "I can tell the difference between `say` and `say for seconds`.",
     "I can sequence dialogue between two sprites."],
    "Ask: \"If your sprite could say ONE thing to the world, what would it be?\" Type their exact words into the block — instant ownership.",
    ["Demo `say Hello! for 2 seconds` — then plain `say Hello!`. Ask what the difference is. (Plain `say` never goes away.)",
     "Show how to clear a stuck bubble with an empty `say`.",
     "Add a second sprite and build a short conversation using `wait` to take turns. This is the child's first multi-sprite timing problem.",
     "Let them write a 4-line conversation with their own words."],
    ["Both sprites talk over each other → each sprite needs a `wait` matching the other's speaking time.",
     "Speech bubble never disappears → they used `say` instead of `say for seconds`; add an empty `say` to clear.",
     "Child writes very long text that overflows → keep bubbles under about 8 words."],
    ["What is the difference between `say` and `say for 2 seconds`? → The second one clears itself.",
     "How do I make sprite B wait its turn? → Give it a `wait` as long as sprite A's speech.",
     "How do I clear a speech bubble? → `say` with nothing in it."],
    "Give a two-line script and let them fill in only the words.",
    "Ask them to time a 3-sprite conversation so nobody interrupts — real timing reasoning.",
    ("Makes one sprite speak with support.",
     "Uses say-for-seconds correctly and sequences two sprites.",
     "Times a multi-sprite conversation so it reads naturally."))

CONCEPTS["costumes"] = C(
    "Costumes and switching", "Looks",
    ["switch costume to ()", "next costume", "costume number"],
    ["Costume — one of the pictures a sprite can wear.",
     "Frame — a single picture in an animation."],
    ["I can add and name costumes.",
     "I can switch costumes with a block.",
     "I can explain how switching costumes creates animation."],
    "Flip-book moment: draw two stick figures on paper corners and flip them. \"That is exactly what Scratch does — pictures swapped fast.\"",
    ["Open the Costumes tab. Show the sprite already has two costumes; click between them and watch the sprite change.",
     "Demo `next costume` clicked repeatedly — the child sees the walk cycle by hand.",
     "Explain the key idea: animation = costume change + a small wait, repeated.",
     "Set the task: make the character look like it is walking on the spot."],
    ["Costumes flick too fast to see → add `wait 0.2 seconds` between switches.",
     "Child edits the costume by accident with the paint tools → point out the Costumes tab versus the Code tab.",
     "Only one costume exists → add one from the library before coding."],
    ["What is a costume? → One of the pictures a sprite can wear.",
     "Why does the sprite look like it is walking? → The picture swaps quickly.",
     "What block moves to the next picture? → `next costume`."],
    "Provide the sprite with two clear costumes already loaded; the child only adds the wait.",
    "Ask for a 4-costume animation where the timing changes (fast run versus slow walk).",
    ("Switches costume when told which block to use.",
     "Builds a costume-change animation with sensible timing.",
     "Designs a multi-costume animation and adjusts timing for effect."))

CONCEPTS["animation-loop"] = C(
    "Repeat: your first loop", "Control",
    ["repeat ()", "next costume", "wait () seconds"],
    ["Loop — a block that repeats the code inside it.",
     "Repeat — do something a set number of times.",
     "Iteration — one pass through a loop."],
    ["I can use a repeat block to avoid copying code.",
     "I can choose a sensible number of repeats.",
     "I can explain what a loop does in my own words."],
    "Ask the child to clap 20 times while you count. Then say: \"Would you rather I wrote 'clap' 20 times, or just said 'clap 20 times'?\" That is a loop.",
    ["Show the long way first: four `next costume` + `wait` pairs stacked. Deliberately tedious.",
     "Now wrap ONE pair in `repeat 4`. Run both. Same result, far less code. Let that land.",
     "Change the repeat number and predict the effect. Establish the loop count as a control.",
     "Task: animate the sprite walking across the stage using `repeat` with move + next costume inside."],
    ["Blocks placed under the loop instead of inside it → show the C-shape 'mouth' swallowing the blocks.",
     "Animation is a blur → a `wait` is missing inside the loop.",
     "Child repeats the whole script instead of the repeating part → ask 'which bit actually repeats?'"],
    ["What does `repeat 10` do? → Runs the blocks inside it ten times.",
     "Why use a loop instead of copying blocks? → Less code, easier to change.",
     "Where must the blocks go? → Inside the C-shape."],
    "Pre-build the inside of the loop; the child only wraps it and sets the number.",
    "Ask them to nest a loop inside a loop and predict the total number of runs (a genuine stretch).",
    ("Uses a loop when told to.",
     "Chooses a loop to remove repetition and sets a sensible count.",
     "Explains loops as repetition and uses nested loops deliberately."))

CONCEPTS["forever"] = C(
    "Forever loops", "Control",
    ["forever", "stop [all]"],
    ["Forever — a loop that never ends until the project stops.",
     "Condition — something that is either true or false."],
    ["I can use a forever loop for continuous behaviour.",
     "I can explain when to use forever instead of repeat.",
     "I can stop a forever loop."],
    "Ask: \"Which of these should run forever — a heartbeat, or blowing out birthday candles?\" Sorting behaviours into 'always' and 'once' is the whole concept.",
    ["Demo `repeat 10 [next costume]` then swap it for `forever`. The child sees the animation never stop.",
     "Explain the rule: use `repeat` for a set number, `forever` for behaviour that should always be on (like checking, patrolling, animating).",
     "Show that nothing placed UNDER a forever loop ever runs — a classic trap. Demonstrate it deliberately.",
     "Task: make a sprite patrol back and forth forever."],
    ["Blocks placed under `forever` never run → move them inside, or into a separate script.",
     "Project cannot be stopped → use the red stop sign, or `stop all`.",
     "Everything is in one giant forever loop → split into separate scripts, one behaviour each."],
    ["When would you choose forever over repeat? → For behaviour that should always run.",
     "What happens to blocks placed under a forever loop? → They never run.",
     "How do you stop it? → Red stop sign or `stop all`."],
    "Give a working forever loop and have them change only what is inside it.",
    "Two forever loops on two sprites at once — ask them to explain how both run at the same time.",
    ("Uses forever when directed.",
     "Chooses forever appropriately and knows blocks below it never run.",
     "Runs several forever scripts in parallel and reasons about them."))

CONCEPTS["events-key"] = C(
    "Key press events", "Events",
    ["when [] key pressed", "when green flag clicked"],
    ["Event — something that happens and starts a script.",
     "Hat block — the rounded block on top that listens for an event."],
    ["I can start a script with a key press.",
     "I can control a sprite with several keys.",
     "I can explain what an event is."],
    "Ask: \"What makes a doorbell ring?\" Someone presses it. Code can listen for a press too — that is an event.",
    ["Demo `when space key pressed → say Hi!`. Press space. The magic is that the child, not the flag, caused it.",
     "Add `when right arrow key pressed → change x by 10`. Now they are driving a sprite.",
     "Build all four arrow keys together. Point out four separate scripts, each listening independently.",
     "Task: drive the sprite around the stage with the arrow keys."],
    ["Only one arrow works → each key needs its OWN hat block and script.",
     "Sprite moves the wrong way → `change x by -10` for left; negative means backwards.",
     "Nothing happens → the Scratch stage needs focus; click the stage once."],
    ["What is an event? → Something that happens and starts a script.",
     "How many scripts do I need for four arrow keys? → Four, one per key.",
     "How do I move left? → Change x by a negative number."],
    "Set up two keys (left/right) only, and let them add up/down themselves.",
    "Ask them to add a key that makes the sprite jump or change size — inventing their own control.",
    ("Uses one key-press event with help.",
     "Builds four independent key scripts to drive a sprite.",
     "Designs a custom control scheme and explains event-driven code."))

CONCEPTS["events-click"] = C(
    "Click and interact", "Events",
    ["when this sprite clicked", "when backdrop switches to ()", "broadcast ()"],
    ["Interaction — the project responding to the player.",
     "Trigger — the thing that starts a script."],
    ["I can make a sprite respond to being clicked.",
     "I can build a simple interactive scene.",
     "I can choose the right trigger for a behaviour."],
    "Point at any app on screen: \"Everything you tap does something. Today your sprites become tappable.\"",
    ["Demo `when this sprite clicked → play sound + next costume`. Instant, satisfying feedback.",
     "Add a second sprite with a different reaction. The stage becomes a toy.",
     "Discuss trigger choice: flag = start, key = control, click = interaction.",
     "Task: build a scene where three sprites each do something different when clicked."],
    ["Click does nothing → the child clicked the sprite in the sprite LIST, not on the stage.",
     "The reaction is too fast to notice → add a `wait` or a longer effect.",
     "Wrong sprite selected while coding → check the highlighted thumbnail."],
    ["Which trigger for a character that reacts when tapped? → `when this sprite clicked`.",
     "Which trigger starts the whole project? → `when green flag clicked`.",
     "Where must you click to test? → On the sprite on the stage."],
    "One sprite, one reaction, chosen by the child (sound is the easiest win).",
    "Ask for a click that changes the backdrop as well — the first taste of scene changes.",
    ("Adds a click reaction with support.",
     "Builds several sprites with distinct click reactions.",
     "Chooses triggers deliberately and explains why each fits."))

CONCEPTS["coordinates"] = C(
    "Coordinates: x and y", "Motion",
    ["go to x: () y: ()", "change x by ()", "change y by ()", "set x to ()", "x position", "y position"],
    ["x — how far left or right (-240 to 240).",
     "y — how far up or down (-180 to 180).",
     "Origin — the centre of the stage, where x and y are both 0."],
    ["I can read a sprite's x and y position.",
     "I can send a sprite to an exact place.",
     "I can explain which way x and y increase."],
    "Play Battleships for 90 seconds on paper. Grid references ARE coordinates — the child already understands this.",
    ["Drag the sprite around and watch the x/y readout change. Let the child predict the sign before you drag (left is negative).",
     "Demo `go to x: 0 y: 0` — the sprite snaps to the centre. Then the four corners; have them predict each.",
     "Contrast `set x to 100` (jump to) with `change x by 100` (move by). This distinction matters for the rest of the course.",
     "Task: place four sprites at four given coordinates without dragging them."],
    ["Confusing x and y → 'x is a crossing, side to side' works well as a memory hook.",
     "Sprite vanishes off-stage → the value exceeded the range; keep x within -240..240.",
     "Using `set` when they mean `change` → read both aloud: 'go to' versus 'move by'."],
    ["What is at x 0, y 0? → The centre of the stage.",
     "Which way does y increase? → Upwards.",
     "Difference between `set x to 10` and `change x by 10`? → Jump to 10 versus move 10 further."],
    "Give a printed stage grid to point at before typing any numbers.",
    "Ask them to move a sprite in a diamond using only `go to x y` — planning four coordinate pairs.",
    ("Uses coordinates by trial and error.",
     "Places sprites accurately and distinguishes set from change.",
     "Plans coordinate paths in advance and reasons about signs."))

CONCEPTS["glide"] = C(
    "Glide for smooth movement", "Motion",
    ["glide () secs to x: () y: ()", "glide () secs to [random position]", "point towards ()"],
    ["Glide — move smoothly to a place over a set time.",
     "Smooth motion — movement the eye reads as continuous."],
    ["I can make a sprite glide instead of jump.",
     "I can control how long a movement takes.",
     "I can choose between glide and move for an effect."],
    "Show the same journey twice: once with `go to` (teleport) and once with `glide` (travel). Ask which looks better in a game. They will always say glide.",
    ["Demo `go to x: 200 y: 0` — a teleport. Then `glide 1 secs to x: 200 y: 0`. Same destination, different feel.",
     "Change the seconds: 0.2 (fast) versus 3 (slow). Timing is now an expressive tool.",
     "Combine glide with `point towards` so the sprite faces where it travels.",
     "Task: make a rocket glide across the stage and arrive facing the right way."],
    ["Glide looks jumpy → the duration is too short; try 1 second or more.",
     "Sprite arrives sideways → add `point in direction 90` or set the rotation style.",
     "Nothing is visible because the glide is inside a fast loop → slow it down to see it."],
    ["What does the seconds number in glide control? → How long the movement takes.",
     "When would you use glide over go to? → When the movement should be seen.",
     "How do I make a sprite face where it is going? → `point towards` it."],
    "Pre-fill the destination coordinates so they only tune the seconds.",
    "Ask for a glide path with three legs at different speeds to convey a mood (panicked versus calm).",
    ("Uses glide with given values.",
     "Chooses glide versus go-to and tunes timing purposefully.",
     "Uses timing expressively across a multi-leg journey."))

CONCEPTS["backdrops"] = C(
    "Backdrops and scenes", "Looks",
    ["switch backdrop to ()", "next backdrop", "when backdrop switches to ()"],
    ["Backdrop — the picture behind everything on the stage.",
     "Scene — one setting in a story or game."],
    ["I can add and switch backdrops.",
     "I can change scene during a project.",
     "I can trigger sprite behaviour when the scene changes."],
    "Ask: \"How does a film show that we've moved to a new place?\" The background changes. Same trick here.",
    ["Add two backdrops from the library. Switch between them by clicking — establish the Stage as a thing you can code.",
     "Demo `switch backdrop to` inside a script so the scene changes during the project.",
     "Introduce `when backdrop switches to` on a sprite — now scenery drives characters. This is the seed of broadcasting.",
     "Task: build a two-scene story where a sprite appears only in scene two."],
    ["Backdrop code added to a sprite instead of the Stage → click the Stage in the sprite list.",
     "Sprite visible in the wrong scene → use `hide` and `show` alongside the backdrop switch.",
     "Scene changes instantly with no time to read → add a `wait`."],
    ["Where does backdrop code usually live? → On the Stage.",
     "How can a sprite know the scene changed? → `when backdrop switches to`.",
     "How do I hide a sprite in a scene? → `hide` then `show` later."],
    "Two backdrops only, switched by a key press they choose.",
    "Three scenes with sprites appearing and disappearing correctly in each — real scene management.",
    ("Switches backdrops manually.",
     "Codes a scene change and coordinates one sprite with it.",
     "Manages a multi-scene project with sprites correctly shown and hidden."))

CONCEPTS["size-effects"] = C(
    "Size, show, hide and effects", "Looks",
    ["set size to () %", "change size by ()", "show", "hide", "change [ghost] effect by ()", "clear graphic effects"],
    ["Effect — a visual change such as ghost (transparency) or colour.",
     "Percent — size compared with the original (100% is normal)."],
    ["I can change a sprite's size.",
     "I can show and hide sprites.",
     "I can use effects for feedback such as fading."],
    "Ask: \"How does a game show you that you picked something up?\" It vanishes, shrinks or flashes. Today we build that feedback.",
    ["Demo `set size to 50%` and `200%`. Then `change size by 10` inside a repeat for a grow animation.",
     "Demo `hide` and `show`. Stress the classic bug: a sprite left hidden at the end will be invisible next run.",
     "Teach the reset habit: every project starts by setting size, position and show. Model it now — it prevents dozens of future bugs.",
     "Demo `change ghost effect by 25` repeated for a fade-out. Task: make an item fade and vanish when collected."],
    ["Sprite invisible on next run → it was hidden and never shown; add `show` at the start.",
     "Sprite grows forever across runs → `set size to 100` at the start, not `change size`.",
     "Ghost effect persists → `clear graphic effects` at the start."],
    ["Why set size at the start of a project? → So it resets each run.",
     "What does the ghost effect do? → Makes the sprite see-through.",
     "How do I make a collected item disappear? → `hide` it."],
    "Give the reset block stack ready-made; the child adds only the effect.",
    "Ask for a collect animation combining grow, fade and hide together.",
    ("Changes size or visibility when told.",
     "Uses show/hide/size with a reset at the start of the project.",
     "Combines effects into polished feedback and always resets state."))

CONCEPTS["sound-play"] = C(
    "Sound and music", "Sound",
    ["start sound ()", "play sound () until done", "stop all sounds", "change volume by ()"],
    ["Sound — an audio clip attached to a sprite.",
     "Until done — wait for the sound to finish before moving on."],
    ["I can add a sound from the library.",
     "I can play a sound on an event.",
     "I can explain the difference between start sound and play until done."],
    "Play a game clip with the sound off, then on. Ask which one feels like a real game. Sound is the cheapest polish there is.",
    ["Open the Sounds tab and add one from the library. Show that sounds belong to a sprite.",
     "Demo `start sound` (carry straight on) versus `play sound until done` (wait for it). This is a genuine timing distinction.",
     "Attach a sound to a click or a collision so it means something.",
     "Task: give every interaction in the project its own sound."],
    ["Sounds overlap into noise → use `play until done`, or stop other sounds first.",
     "No sound at all → check the sprite has the sound and system volume is up.",
     "Sound plays once and never again → check the trigger, not the sound."],
    ["Difference between start sound and play until done? → One continues immediately, one waits.",
     "Where do a sprite's sounds live? → In its Sounds tab.",
     "How would you stop everything? → `stop all sounds`."],
    "Pick the sound for them and let them attach it to one event.",
    "Ask them to build a 4-sound rhythm using waits — bridging into the music work later.",
    ("Adds and plays a sound with help.",
     "Attaches sounds to events and picks the right play block.",
     "Uses sound deliberately for feedback and timing."))

CONCEPTS["wait-timing"] = C(
    "Wait and timing", "Control",
    ["wait () seconds", "wait until <>"],
    ["Wait — pause a script for a set time.",
     "Timing — controlling when things happen."],
    ["I can pause a script for a set time.",
     "I can use waits to sequence two sprites.",
     "I can explain why timing matters in animation."],
    "Clap a rhythm and have the child copy it, then clap the same claps with no gaps. Timing is the difference between music and noise.",
    ["Add `wait 1 seconds` between two `say` blocks and run. The pause becomes visible.",
     "Show fractional waits (0.1, 0.2) for animation smoothness — children rarely discover these alone.",
     "Coordinate two sprites so they alternate correctly using matching waits.",
     "Task: choreograph a short scene where three things happen in order."],
    ["Everything appears to happen at once → waits are missing.",
     "Animation is jerky → the wait is too long; try 0.1.",
     "Sprites drift out of sync over time → prefer broadcasts later; note this as a limitation now."],
    ["How do I make a sprite pause? → `wait` with a number of seconds.",
     "Why use 0.1 instead of 1? → For smooth animation.",
     "How do two sprites take turns? → Match one's wait to the other's action."],
    "Give the script and let them tune only the wait values by ear.",
    "Ask them to sync three sprites to a beat — a genuine timing challenge.",
    ("Adds waits when prompted.",
     "Uses waits to sequence and smooth animation.",
     "Choreographs multiple sprites with accurate timing."))

CONCEPTS["if-basic"] = C(
    "If ... then: making decisions", "Control",
    ["if <> then", "touching ()?", "key () pressed?"],
    ["Condition — something that is either true or false.",
     "If — do something only when a condition is true.",
     "Boolean — a true/false value (the pointy blocks)."],
    ["I can use an if block to make code decide.",
     "I can put a condition into the pointy slot.",
     "I can explain why an if usually sits inside a forever loop."],
    "Say: \"IF it rains, THEN take an umbrella.\" Ask for three more if-then rules from their own life. They already think in conditionals.",
    ["Draw the shape: `if <condition> then <action>`. Point out the condition slot is POINTY — only pointy blocks fit.",
     "Demo `if <key space pressed?> then <say Jump!>` inside a `forever`. Crucial teaching point: without forever, it is checked once only.",
     "Deliberately remove the forever and show it failing. The child must see WHY checking must repeat.",
     "Task: make the sprite react when it touches another sprite."],
    ["The if runs once and never again → it needs to be inside a `forever` loop.",
     "Condition slot left empty → nothing happens; the pointy block is missing.",
     "Child uses `if` where they need `wait until` → discuss the difference explicitly."],
    ["What shape block goes in the condition slot? → A pointy (boolean) one.",
     "Why put an if inside a forever? → So it keeps checking.",
     "What does 'condition' mean? → Something true or false."],
    "Provide the forever loop pre-built; the child drops in the condition only.",
    "Two conditions with two different reactions — leading naturally into if/else.",
    ("Builds an if with support and often omits the loop.",
     "Uses if inside forever with a correct condition.",
     "Explains conditions as true/false and chooses if versus wait-until."))

CONCEPTS["sensing-touch"] = C(
    "Sensing: touching things", "Sensing",
    ["touching ()?", "touching color ()?", "distance to ()"],
    ["Sensing — code that detects what is happening.",
     "Collision — when two sprites touch."],
    ["I can detect when sprites touch.",
     "I can react to a collision.",
     "I can use colour sensing for tracks and walls."],
    "Ask: \"In a racing game, how does the game know you crashed?\" It senses the touch. Today we give sprites senses.",
    ["Demo `if <touching Sprite2?> then <say Ouch!>` inside forever. Drag the sprite into the other one live — the reaction proves it.",
     "Show `touching color` with a coloured track or wall. Use the eyedropper carefully — colour must match exactly.",
     "Discuss what should happen ON collision: score, sound, hide, bounce. Collision is a trigger for design decisions.",
     "Task: build a collect-or-avoid interaction."],
    ["Colour sensing unreliable → the eyedropper picked a slightly different shade; re-pick from the exact pixel.",
     "Collision fires many times per second → hide the item or add a wait so it triggers once.",
     "Sprites look like they touch but do not → transparent edges in the costume."],
    ["How does a game know two things collided? → Touching sensing.",
     "Why might colour sensing fail? → The colour is not an exact match.",
     "How do I stop a collision firing repeatedly? → Hide the object or wait."],
    "One collision, one reaction (a sound) — nothing more.",
    "Different reactions for different sprites — good and bad objects.",
    ("Detects a collision with help.",
     "Uses touching sensing to drive a reaction reliably.",
     "Handles repeated-trigger problems and uses colour sensing accurately."))

CONCEPTS["sensing-key"] = C(
    "Smooth control with sensing", "Sensing",
    ["key () pressed?", "forever", "if <> then"],
    ["Polling — repeatedly checking whether something is true.",
     "Responsive — reacting instantly to the player."],
    ["I can move a sprite using key-pressed sensing.",
     "I can explain why sensing is smoother than key events.",
     "I can build responsive four-way control."],
    "Let the child drive with `when key pressed` and feel the stutter, then with sensing and feel it glide. The comparison teaches itself.",
    ["Rebuild yesterday's arrow-key control using `forever + if <key pressed?>` instead of hat blocks.",
     "Race the two versions side by side. The sensing version has no repeat-delay stutter — this is a real engineering insight.",
     "Explain the trade-off: events are simple, polling is smooth. Games use polling.",
     "Task: convert the player sprite to smooth four-way control."],
    ["Sprite moves too fast → reduce the change value to 3 or 4.",
     "Diagonal movement impossible → all four ifs must be in the SAME forever loop.",
     "Old key-event scripts left in place fight the new ones → delete the old scripts."],
    ["Why is sensing smoother than key events? → It checks constantly with no key-repeat delay.",
     "How do you allow diagonal movement? → Put all the ifs in one forever loop.",
     "What does polling mean? → Checking over and over."],
    "Convert two directions only, then let them mirror the pattern.",
    "Add speed control — holding shift moves faster (nested conditions).",
    ("Copies the sensing pattern.",
     "Builds smooth four-way control and explains the advantage.",
     "Tunes responsiveness and handles diagonals and speed states."))

CONCEPTS["random"] = C(
    "Random numbers", "Operators",
    ["pick random () to ()", "go to [random position]"],
    ["Random — unpredictable, different each time.",
     "Range — the lowest and highest possible values."],
    ["I can use pick random in a block.",
     "I can choose a sensible range.",
     "I can explain why randomness makes games replayable."],
    "Roll a dice three times. \"Could you predict that? No. That is what makes games worth playing twice.\"",
    ["Drop `pick random 1 to 10` into a `say` block and click it repeatedly. The changing number makes the idea concrete.",
     "Use it for position: `go to x: (pick random -200 to 200) y: (pick random -150 to 150)`. Discuss why those numbers — stage bounds.",
     "Use it for timing: `wait (pick random 1 to 3) seconds` so events feel natural rather than mechanical.",
     "Task: make a target appear in an unpredictable place each time."],
    ["Sprite appears half off-stage → the range is too wide; keep within roughly -200..200 and -150..150.",
     "Random re-rolled every frame so the sprite vibrates → pick the number once, outside the loop or before a wait.",
     "Range typed backwards (10 to 1) → still works, but discuss readability."],
    ["Why use random in a game? → It makes each play different.",
     "What range keeps a sprite on stage? → About -200 to 200 for x.",
     "Why is my sprite shaking? → Random is being re-picked constantly."],
    "Give the block with the range filled in; the child predicts and tests outcomes.",
    "Ask for random size AND position AND wait together for a lively scene.",
    ("Uses a random block provided for them.",
     "Chooses sensible ranges and applies random to position or timing.",
     "Combines multiple random values and reasons about distribution and stage bounds."))

CONCEPTS["variable-score"] = C(
    "Variables: keeping score", "Variables",
    ["set () to ()", "change () by ()", "show variable ()", "hide variable ()"],
    ["Variable — a named box that stores a value you can change.",
     "Set — put a specific value in the box.",
     "Change by — add to what is already there."],
    ["I can make a variable and name it well.",
     "I can reset a score at the start and add to it during play.",
     "I can explain the difference between set and change."],
    "Hold up a physical box or cup labelled 'score' and drop counters in. The variable is the box; the number inside changes. This physical anchor sticks.",
    ["Make a variable together and NAME it properly ('score', not 'thing'). Naming is a real programming habit — start it now.",
     "Demo `change score by 1` on a click. The stage readout moves — immediate feedback.",
     "Teach the golden rule: `set score to 0` when the flag is clicked. Show the bug first by omitting it and running twice.",
     "Task: add a working score to a collecting game."],
    ["Score keeps its old value between runs → missing `set score to 0` at the start.",
     "Score jumps up by many at once → the change block is inside a fast forever loop; hide the item or add a wait.",
     "Variable created 'for this sprite only' when it should be for all → check the option when creating it."],
    ["Difference between set and change? → Set puts a value in; change adds to it.",
     "Why set score to 0 at the start? → So each game begins fresh.",
     "What is a variable? → A named box holding a value."],
    "Create the variable for them; the child adds only the `change by 1`.",
    "Add a high-score variable that only updates when the score beats it — real conditional logic.",
    ("Uses a variable that is set up for them.",
     "Creates, resets and updates a score correctly.",
     "Uses several variables and reasons about when each should reset."))

CONCEPTS["if-else"] = C(
    "If ... else: two paths", "Control",
    ["if <> then else", "not <>"],
    ["If-else — do one thing when true, a different thing when false.",
     "Branch — a path the code can take."],
    ["I can use if-else for two outcomes.",
     "I can decide when else is needed.",
     "I can trace which branch runs."],
    "Ask: \"IF you finish your homework, THEN you play — ELSE?\" They will finish the sentence. That is if-else.",
    ["Show two separate ifs with opposite conditions, then replace with one if-else. Cleaner and cannot both run.",
     "Demo a right/wrong answer check: correct → cheer, otherwise → try again.",
     "Trace it aloud together: 'the condition is false, so we take the else path'. Tracing is a core debugging skill.",
     "Task: give the game a win message and a lose message."],
    ["Both messages appear → two ifs used instead of if-else, or conditions overlap.",
     "Else branch never runs → the condition is always true; test it directly.",
     "Blocks dropped between the if and else sections → check they are in the correct mouth."],
    ["When do you need else? → When there are exactly two outcomes.",
     "If the condition is false, which part runs? → The else part.",
     "Can both branches run? → No, only one."],
    "Fill in one branch for them; the child writes the other.",
    "Nest an if inside an else for three outcomes — win, draw, lose.",
    ("Uses if-else when prompted.",
     "Chooses if-else correctly for two outcomes and traces the branch.",
     "Nests conditionals for multiple outcomes and explains the flow."))

CONCEPTS["repeat-until"] = C(
    "Repeat until", "Control",
    ["repeat until <>", "wait until <>", "stop [this script]"],
    ["Repeat until — keep going until a condition becomes true.",
     "Loop condition — the test that ends a loop."],
    ["I can use repeat until for goal-driven loops.",
     "I can choose between forever, repeat and repeat until.",
     "I can end a loop with a condition."],
    "Say: \"Keep stirring until it's smooth.\" Not ten times — UNTIL. Real instructions work this way.",
    ["Demo `repeat until <touching goal?> [move 5 steps]`. The sprite travels exactly as far as needed, no more.",
     "Compare all three loops explicitly: repeat (set number), forever (never ends), repeat until (goal).",
     "Show `wait until` as the pause version of the same idea.",
     "Task: make a sprite chase until it catches the target, then celebrate."],
    ["Loop never ends → the condition can never become true; test it separately.",
     "Loop ends immediately → the condition was already true at the start.",
     "Child uses forever plus if when repeat-until is cleaner → compare both versions."],
    ["Which loop for 'until you reach the goal'? → repeat until.",
     "Why might a repeat-until never stop? → The condition never becomes true.",
     "What does wait until do? → Pauses the script until the condition is true."],
    "Provide the condition; the child assembles the loop.",
    "Ask for a loop ending on two conditions using `or`.",
    ("Uses repeat until when given the condition.",
     "Chooses the right loop type for the job and writes the condition.",
     "Debugs non-terminating loops and combines conditions."))

CONCEPTS["mouse-follow"] = C(
    "Follow the mouse", "Motion",
    ["point towards [mouse-pointer]", "go to [mouse-pointer]", "mouse x", "mouse y", "distance to ()"],
    ["Mouse pointer — the arrow the player controls.",
     "Follow — continuously move towards a target."],
    ["I can make a sprite follow the mouse.",
     "I can make a sprite look at the mouse.",
     "I can use following for paddles and characters."],
    "Ask: \"How does a guard dog in a game know where you are?\" It points at you, constantly. Let's build eyes that follow.",
    ["Demo `forever [point towards mouse-pointer]`. The sprite watches the cursor — genuinely delightful for this age.",
     "Then `forever [go to mouse-pointer]` — the sprite becomes the cursor. Discuss when each is useful.",
     "Show constrained following: `set x to (mouse x)` only, for a paddle that slides on one axis.",
     "Task: build a paddle or a character whose eyes track the mouse."],
    ["Sprite spins wildly → rotation style; set it to left-right or all-around as appropriate.",
     "Sprite sits exactly on the pointer and hides it → offset with `change y by`.",
     "Paddle moves vertically when it should not → use `set x to mouse x` only, not `go to`."],
    ["How do you make a sprite face the mouse? → `point towards mouse-pointer`.",
     "How do you make a paddle slide horizontally only? → `set x to mouse x`.",
     "What must the following code sit inside? → A forever loop."],
    "Give the forever loop; the child chooses point-towards or go-to and tests both.",
    "Make the sprite follow only when the mouse is close (using `distance to`).",
    ("Copies a following script.",
     "Chooses the right following technique for the job.",
     "Constrains and conditions following behaviour deliberately."))

CONCEPTS["bounce"] = C(
    "Bouncing and edges", "Motion",
    ["if on edge, bounce", "set rotation style ()", "turn () degrees"],
    ["Edge — the boundary of the stage.",
     "Bounce — reverse direction on hitting something."],
    ["I can keep a sprite on the stage.",
     "I can make a sprite bounce off edges.",
     "I can fix upside-down sprites with rotation style."],
    "Bounce a ball off a wall in the room (or mime it). Ask which way it goes. Physics they already know becomes code.",
    ["Demo `forever [move 10 steps, if on edge bounce]`. A patrolling sprite in two blocks.",
     "The sprite will go upside-down — let it happen, then fix it with rotation style left-right. Bug-then-fix teaches better than warning first.",
     "Add randomness: `point in direction (pick random 1 to 360)` at the start for unpredictable paths.",
     "Task: build a bouncing ball or a patrolling enemy."],
    ["Sprite is upside-down → set rotation style to left-right.",
     "Sprite gets stuck vibrating on an edge → move it inward, or increase the step size.",
     "Bounce block placed outside the loop → nothing bounces; it must be inside."],
    ["Which block keeps a sprite on stage? → `if on edge, bounce`.",
     "Why is my sprite upside-down? → Rotation style is all-around.",
     "How do I make each run different? → Start at a random direction."],
    "Provide move + bounce and let them only add the rotation fix.",
    "Two bouncing sprites that also react when they hit each other.",
    ("Uses the bounce block when given it.",
     "Builds reliable bouncing movement and fixes rotation.",
     "Combines bouncing with randomness and sprite collisions."))

CONCEPTS["debug-basics"] = C(
    "Finding and fixing bugs", "Design",
    ["stop [all]", "say ()", "wait () seconds"],
    ["Bug — a mistake that makes a program behave wrongly.",
     "Debug — to find and fix a bug.",
     "Test — to run code deliberately to see what happens."],
    ["I can describe what a program does wrongly.",
     "I can find the block causing a bug.",
     "I can fix a bug and re-test."],
    "Say: \"Every professional programmer's code is broken most of the day. Finding bugs is the actual job — and you're about to be good at it.\" This reframes failure permanently.",
    ["Give the child a project you have broken on purpose. Ask first: what SHOULD it do, and what does it do instead? Naming the gap is step one.",
     "Teach the three moves: (1) run it and watch closely, (2) click a single script to test it alone, (3) add a `say` to see what the code thinks is happening.",
     "Slow it down with waits so the failure becomes visible.",
     "Fix it, then re-run to confirm. Insist on the re-test — fixing without verifying is a habit worth preventing early."],
    ["Child changes many things at once → change ONE thing, then test. Otherwise you cannot tell what worked.",
     "Child deletes the whole script in frustration → encourage isolating instead; keep a copy first.",
     "Child assumes the computer is wrong → the computer does exactly what it was told; find what it was told."],
    ["What is a bug? → A mistake making the program behave wrongly.",
     "What is the first thing to do? → Say what it should do versus what it does.",
     "Why change one thing at a time? → So you know which change fixed it."],
    "Debug together, thinking aloud so the child hears your reasoning; then let them lead the next one.",
    "Give a project with two independent bugs and ask them to log what they tried.",
    ("Spots that something is wrong but not where.",
     "Isolates and fixes a bug, then re-tests.",
     "Debugs systematically, one change at a time, and explains the cause."))

CONCEPTS["game-win-lose"] = C(
    "Winning and losing", "Design",
    ["stop [all]", "switch backdrop to ()", "broadcast ()", "if <> then"],
    ["Win condition — the rule that means the player has won.",
     "Lose condition — the rule that ends the game in failure.",
     "Game state — whether the game is playing, won or lost."],
    ["I can define a clear win condition.",
     "I can define a lose condition.",
     "I can end the game and tell the player what happened."],
    "Ask: \"How do you know when you've WON a game?\" Then: \"What if a game never told you?\" Feedback is the point.",
    ["Decide the rules together and write them in plain English FIRST: 'You win when score = 10. You lose when lives = 0.' Design before code.",
     "Turn each sentence into an if: `if <score = 10> then [say You win!, stop all]`.",
     "Add a backdrop change for the ending so the win feels real.",
     "Task: give the game both endings and test each one deliberately."],
    ["Game never ends → the condition is never exactly met; use `>` rather than `=` where values can skip.",
     "Win message flashes and vanishes → `stop all` ran before the message could be read; say first, then stop.",
     "Game ends instantly → the condition was true at the start; reset variables first."],
    ["What is a win condition? → The rule that means you have won.",
     "Why use > instead of = for a score check? → The score might skip past the exact number.",
     "How do you tell the player? → A message and a backdrop change."],
    "Write the rules in English with them, then code only the win path.",
    "Add a third state — a draw or a time-out — and manage all three.",
    ("Adds an ending when prompted.",
     "Defines and codes both win and lose conditions with feedback.",
     "Manages game states cleanly and tests each ending deliberately."))

CONCEPTS["l1-capstone"] = C(
    "Level 1 capstone project", "Design",
    ["all Level 1 blocks"],
    ["Capstone — a project that pulls together everything learned.",
     "Iteration — improving a project through repeated testing."],
    ["I can plan a project before I build it.",
     "I can combine motion, events, loops, sensing and variables.",
     "I can test, fix and present my project."],
    "Say: \"Today you're not following instructions — you're the designer. I'm just your engineer if you get stuck.\" The shift in ownership is the point.",
    ["Plan on paper first: what is the goal, who is the player, what are the rules, how do you win and lose? Ten minutes of planning saves thirty of confusion.",
     "Build the player controls first and test. Then the objective. Then scoring. Then endings. One layer at a time, testing each.",
     "Insist on testing after every layer — this is the professional habit the whole level has been building towards.",
     "Finish with a presentation: the child demonstrates and explains their code choices to you or a parent."],
    ["Child plans something far too big → cut it to one screen and one mechanic; a finished small game beats an unfinished epic.",
     "Everything is built before anything is tested → stop and test now, layer by layer.",
     "Child copies a previous project exactly → ask for one rule that is genuinely theirs."],
    ["What are your win and lose conditions? → (child's own answer)",
     "Which part will you build and test first? → Player controls.",
     "Which blocks reset your game at the start? → Set score, position, show."],
    "Offer a template with the player controls done, so they design the objective and scoring.",
    "Require two mechanics plus a title screen, and ask them to write brief instructions for a new player.",
    ("Builds with heavy guidance and limited testing.",
     "Plans, builds and tests a complete game with clear rules.",
     "Designs an original game, iterates on feedback and explains their decisions."))


# =====================================================================
# LEVEL 2 — Logic, data and real game engineering
# =====================================================================

CONCEPTS["operators-math"] = C(
    "Maths operators", "Operators",
    ["() + ()", "() - ()", "() * ()", "() / ()", "() mod ()", "round ()"],
    ["Operator — a block that works out a value.",
     "Expression — blocks combined to calculate something.",
     "mod — the remainder after dividing."],
    ["I can use arithmetic blocks inside other blocks.",
     "I can build an expression from a variable and a number.",
     "I can use mod to detect multiples."],
    "Ask: \"If a game gives 10 points per coin and you have 7 coins, how does the game work out your score?\" It calculates. Today code does the maths.",
    ["Drop `(score) * (10)` into a `say` block. Show that green operator blocks fit INSIDE other blocks — this nesting idea is new and important.",
     "Build `set score to (score) + (5)` and compare it with `change score by 5`. Same result, different tools; understanding both matters.",
     "Introduce `mod`: `(score) mod (2) = 0` detects even numbers. Use it for 'every 5th point, speed up'.",
     "Task: make a bonus that awards double points."],
    ["Operator dropped beside a block instead of inside a slot → show the slot highlighting as you hover.",
     "Division gives a long decimal → wrap it in `round`.",
     "Child nests too deeply to read → build the expression in stages using a helper variable."],
    ["Where do green operator blocks go? → Inside other blocks' slots.",
     "What does mod do? → Gives the remainder.",
     "How do you double a score? → Multiply it by 2."],
    "Pre-build the expression and let them change only the numbers, predicting results.",
    "Ask for a combo multiplier that grows with a streak.",
    ("Uses an operator block placed for them.",
     "Builds correct expressions nested inside other blocks.",
     "Composes multi-step expressions and uses mod purposefully."))

CONCEPTS["operators-compare"] = C(
    "Comparing values", "Operators",
    ["() < ()", "() = ()", "() > ()"],
    ["Comparison — checking how two values relate.",
     "Boolean — a value that is either true or false."],
    ["I can compare a variable with a number.",
     "I can use comparisons as conditions.",
     "I can choose between <, = and > correctly."],
    "Hold up two numbers and ask 'which is bigger?' — then ask how the COMPUTER would know. It compares, and gets true or false.",
    ["Put `(score) > (5)` into a `say` block and click it. It reports true or false — making the invisible boolean visible is the key move here.",
     "Now drop the same comparison into an `if`. The child sees that conditions are just true/false values.",
     "Discuss the classic bug: `= 10` can be missed if the score jumps by 2s. Prefer `> 9` or `>= 10`. This is real defensive thinking.",
     "Task: trigger a level-up when the score passes a threshold."],
    ["Condition using = never fires → the exact value was skipped; use > instead.",
     "Comparison compares text not numbers → check the variable holds a number.",
     "Child reverses < and > → read it aloud: 'score is greater than five'."],
    ["What do comparison blocks give you? → True or false.",
     "Why is > safer than = for scores? → The score might skip the exact value.",
     "How do you check 'at least 10'? → `not (score < 10)` or `score > 9`."],
    "Give the comparison and let them test values to see true/false directly.",
    "Ask for a grade band system: over 90 excellent, over 70 good, otherwise keep trying.",
    ("Uses a comparison provided for them.",
     "Writes correct comparisons and uses them as conditions.",
     "Chooses robust comparisons and reasons about edge cases."))

CONCEPTS["operators-logic"] = C(
    "and, or, not", "Operators",
    ["<> and <>", "<> or <>", "not <>"],
    ["and — true only when BOTH are true.",
     "or — true when EITHER is true.",
     "not — flips true to false."],
    ["I can combine two conditions with and/or.",
     "I can use not to invert a condition.",
     "I can predict whether a combined condition is true."],
    "Say: \"You can have ice cream IF you finish dinner AND it's not a school night.\" Change AND to OR and ask if that's a better deal. They will spot it instantly.",
    ["Build `<touching goal?> and <key space pressed?>` and test both parts separately first, then together.",
     "Make a truth table on paper for and/or with two conditions — four rows. This is genuine computer science and children enjoy it.",
     "Demo `not <touching wall?>` for 'keep moving while free'.",
     "Task: require two conditions for a win — reach the goal AND collect all items."],
    ["`and` used where `or` is meant → walk the truth table; ask when it should be true.",
     "Conditions nested wrongly so the logic inverts → build one condition at a time and test each.",
     "Overly complex condition → split it using a variable such as `ready`."],
    ["When is `A and B` true? → Only when both are true.",
     "When is `A or B` true? → When either is true.",
     "What does not do? → Flips true and false."],
    "Test each condition alone before combining; let the child predict the combination.",
    "Ask for a three-condition rule and have them draw the truth table first.",
    ("Uses a combined condition given to them.",
     "Chooses and/or/not correctly and predicts outcomes.",
     "Reasons with truth tables and simplifies complex conditions."))

CONCEPTS["variable-timer"] = C(
    "Timers and countdowns", "Variables",
    ["timer", "reset timer", "set () to ()", "change () by ()", "wait () seconds"],
    ["Timer — a value that counts time.",
     "Countdown — a timer that decreases to zero.",
     "Pressure — the tension a timer adds to a game."],
    ["I can build a countdown with a variable.",
     "I can end the game when time runs out.",
     "I can use the built-in timer."],
    "Play any game for 20 seconds, then say 'now do it in 10 seconds'. Ask how it felt different. Timers create urgency — that is game design.",
    ["Build the countdown pattern explicitly: `set time to 30`, then `repeat until <time = 0> [wait 1 seconds, change time by -1]`.",
     "Point out the negative change — children often try `change by 1` and wonder why it counts up.",
     "Show the built-in `timer` and `reset timer` as the alternative for elapsed time.",
     "Task: add a 30-second limit and a time-up ending."],
    ["Countdown runs far too fast → the `wait 1 seconds` is missing.",
     "Timer counts up instead of down → change by -1, not 1.",
     "Timer keeps running after the game ends → use `stop all` or a game-state variable."],
    ["How do you count down? → Change the variable by -1 with a wait.",
     "What ends the game? → An if checking the timer reached 0.",
     "What does reset timer do? → Sets the built-in timer back to zero."],
    "Give the countdown loop and let them set the starting time and ending.",
    "Add a bonus that awards extra seconds, and make the timer flash under five seconds.",
    ("Adds a timer with support.",
     "Builds a working countdown that ends the game.",
     "Uses timers for pacing and combines them with bonuses and feedback."))

CONCEPTS["variable-lives"] = C(
    "Lives and health", "Variables",
    ["set () to ()", "change () by ()", "if <> then", "hide", "show"],
    ["Lives — how many attempts the player has left.",
     "Health — a value reduced by damage.",
     "Respawn — returning the player after losing a life."],
    ["I can track lives with a variable.",
     "I can reduce lives on a hit and respawn the player.",
     "I can end the game at zero lives."],
    "Ask: \"Why do games give you three lives instead of one?\" Because instant failure is miserable. Fairness is a design decision.",
    ["Create `lives`, `set lives to 3` at the start. Reduce with `change lives by -1` on a collision.",
     "Solve the repeated-hit bug together: one touch drains all three lives instantly. Fix with a brief invincibility `wait 1 seconds` or by moving the player away.",
     "Add respawn: return the player to the start position after a hit.",
     "Task: add a 3-life system with respawn and a game-over."],
    ["All lives lost from a single collision → the collision fires every frame; add a wait or move the player.",
     "Lives carry over between games → missing reset at the start.",
     "Game over never triggers → check for `lives < 1` rather than exactly 0."],
    ["Why add a wait after losing a life? → So one touch does not drain them all.",
     "What resets lives? → `set lives to 3` at the start.",
     "How do you show lives to the player? → Show the variable, or use sprite icons."],
    "Provide the lives variable and the reset; the child adds the damage and game-over.",
    "Add a health bar using costumes or size, plus a pick-up that restores health.",
    ("Adds lives with guidance.",
     "Implements lives, respawn and game-over correctly.",
     "Designs balanced health systems and handles edge cases."))

CONCEPTS["broadcast"] = C(
    "Broadcast and receive", "Events",
    ["broadcast ()", "broadcast () and wait", "when I receive ()"],
    ["Broadcast — send a message to every sprite.",
     "Receive — react to a message.",
     "Decoupling — sprites cooperating without direct connection."],
    ["I can send a broadcast message.",
     "I can make sprites react to a message.",
     "I can use broadcasts to coordinate sprites."],
    "Ask: \"How does a referee start a race with 8 runners?\" One whistle, everyone reacts. That whistle is a broadcast.",
    ["Rename the message properly ('game-over', not 'message1'). Naming discipline pays off in every later project.",
     "One sprite broadcasts; two sprites receive and each does something different. The power is one-to-many.",
     "Contrast `broadcast` with `broadcast and wait` — the second pauses until all receivers finish. Demonstrate the difference.",
     "Task: replace fragile wait-based timing with broadcasts."],
    ["Nothing reacts → the receiving sprite is listening for a different message name.",
     "Messages left as message1, message2 → unreadable later; rename them now.",
     "Child broadcasts inside a forever loop, firing hundreds per second → move it out or guard it."],
    ["What does a broadcast do? → Sends a message all sprites can hear.",
     "Difference from broadcast-and-wait? → And-wait pauses until receivers finish.",
     "Why is broadcasting better than waits? → Sprites stay in sync reliably."],
    "Give one broadcast and one receiver, then let them add the second receiver.",
    "Build a chain — one broadcast triggers a receiver which broadcasts again — and have them trace the flow.",
    ("Uses a broadcast set up for them.",
     "Names and uses broadcasts to coordinate several sprites.",
     "Designs message flows and chooses broadcast versus broadcast-and-wait deliberately."))

CONCEPTS["broadcast-scenes"] = C(
    "Scenes and game states", "Design",
    ["broadcast ()", "when I receive ()", "switch backdrop to ()", "hide", "show"],
    ["Game state — which part of the game is active (menu, playing, game over).",
     "Scene — a distinct part of the experience.",
     "State machine — moving between states on events."],
    ["I can build a title screen, a game and an end screen.",
     "I can show and hide sprites per scene.",
     "I can move between states with broadcasts."],
    "List the screens of a game they love — menu, play, game over. \"Real games are several small programs that hand over to each other.\"",
    ["Draw the state diagram on paper: Menu → Play → Game Over → Menu. Three boxes and arrows. Children grasp this fast and it structures everything.",
     "Each state gets a broadcast: `start-game`, `game-over`. Each sprite decides what to show or hide on each message.",
     "Build the title screen with a start button (`when this sprite clicked → broadcast start-game`).",
     "Task: wrap an existing game in a title screen and a game-over screen."],
    ["Sprites from the menu still visible during play → each sprite needs a hide on `start-game`.",
     "Game restarts without resetting variables → reset all variables on `start-game`.",
     "Two states run at once → ensure the old state's loops stop, using `stop this script` or a state variable."],
    ["What are the three usual game states? → Menu, playing, game over.",
     "How do you move between them? → Broadcast messages.",
     "What must happen when a new game starts? → Reset variables and sprite visibility."],
    "Provide the menu scene; the child wires the start button and one hide.",
    "Add a pause state and a settings screen — genuinely advanced state handling.",
    ("Adds a title screen with help.",
     "Builds three working states with correct show/hide and resets.",
     "Designs a clean state machine including restart without bugs."))

CONCEPTS["clones-basic"] = C(
    "Clones: many from one", "Control",
    ["when I start as a clone", "create clone of ()", "delete this clone"],
    ["Clone — a copy of a sprite made while the project runs.",
     "Instance — one individual copy.",
     "Spawn — to create a clone."],
    ["I can create clones of a sprite.",
     "I can give clones their own behaviour.",
     "I can delete clones to keep the project fast."],
    "Ask: \"A game has 50 falling asteroids. Did someone make 50 sprites by hand?\" No — one sprite, cloned. This is the biggest efficiency idea in Scratch.",
    ["Demo the three-part pattern clearly: a spawner (`forever [create clone of myself, wait 1]`), the clone's own script (`when I start as a clone`), and cleanup (`delete this clone`).",
     "Stress that `when I start as a clone` runs SEPARATELY for every clone — each has its own position and variables-for-this-sprite-only.",
     "Show what happens without `delete this clone`: hundreds of clones, project slows. Then fix it. Seeing the slowdown teaches the discipline.",
     "Task: build falling objects using one sprite and clones."],
    ["Clones never appear → the original must `hide`, and clones must `show`.",
     "Project grinds to a halt → clones are never deleted; delete when off-screen or touched.",
     "All clones move identically and overlap → give each a random x or a random wait when it starts."],
    ["What block runs for each new clone? → `when I start as a clone`.",
     "Why delete clones? → They pile up and slow the project.",
     "How do you make clones differ? → Randomise position or timing as each starts."],
    "Give the spawner; the child writes only the clone's behaviour.",
    "Add clone types — some worth points, some harmful — using a for-this-sprite-only variable.",
    ("Creates clones by copying a pattern.",
     "Builds spawner, clone behaviour and cleanup correctly.",
     "Manages many clones with varied behaviour and good performance."))

CONCEPTS["clones-advanced"] = C(
    "Clone armies and patterns", "Control",
    ["create clone of ()", "when I start as a clone", "delete this clone", "pick random () to ()"],
    ["Wave — a group of enemies spawned together.",
     "Local variable — a variable that is for this sprite only, so each clone has its own.",
     "Performance — how smoothly a project runs."],
    ["I can spawn waves of clones in patterns.",
     "I can give each clone its own speed or type.",
     "I can keep performance good with cleanup."],
    "Show a shooter or a synchronised swimming pattern. \"Every one of those is the same sprite thinking for itself.\"",
    ["Use `repeat 10 [create clone, wait 0.2]` to build a wave rather than an endless stream. Waves are a design tool.",
     "Introduce for-this-sprite-only variables so each clone carries its own speed. This is the moment cloning becomes powerful.",
     "Build a formation with a loop: clones placed at calculated x positions rather than random ones.",
     "Task: build waves of enemies where each has its own speed."],
    ["All clones share one value unexpectedly → the variable was made 'for all sprites'; it must be for this sprite only.",
     "Clones spawn on top of each other → stagger with a wait or spread by position.",
     "Frame rate collapses → cap the number of clones and delete off-screen ones."],
    ["Why use a for-this-sprite-only variable? → So each clone has its own copy.",
     "How do you make a formation? → Calculate positions in a loop.",
     "How do you protect performance? → Delete clones when they are done."],
    "Provide the wave loop; the child adds per-clone randomness.",
    "Ask for increasing difficulty — each wave faster and larger than the last.",
    ("Spawns multiple clones from a given pattern.",
     "Builds waves with per-clone properties and cleanup.",
     "Designs escalating patterns and reasons about performance."))

CONCEPTS["lists"] = C(
    "Lists: storing many values", "Variables",
    ["add () to []", "delete () of []", "item () of []", "length of []", "[] contains ()?"],
    ["List — a numbered set of values stored together.",
     "Index — the position of an item in a list.",
     "Length — how many items a list holds."],
    ["I can create a list and add items.",
     "I can read an item by its position.",
     "I can use a list for questions, words or high scores."],
    "Hold up a written shopping list. \"One variable holds one thing. A list holds a hundred — and code can walk down it.\"",
    ["Create a list and add three items by hand. The stage display makes the structure visible — keep it shown while teaching.",
     "Demo `item 1 of list` and `item (pick random 1 to (length of list)) of list` for a random pick. This single pattern powers quizzes and jokes.",
     "Show `length of` and `contains` for checking answers.",
     "Task: build a random question picker using two lists (questions and answers)."],
    ["Off-by-one confusion → Scratch lists start at 1, not 0; say it explicitly.",
     "Items duplicate every run → `delete all of list` before adding, or add items only once.",
     "Random pick sometimes errors → the range must be 1 to length, not 0."],
    ["What number is the first item? → 1.",
     "How do you pick a random item? → item (pick random 1 to length of list).",
     "How do you check a list holds something? → The `contains` block."],
    "Pre-fill the list; the child writes only the reading code.",
    "Use two parallel lists so question 3 matches answer 3, and discuss keeping them aligned.",
    ("Adds items to a list with help.",
     "Reads, counts and randomly selects from lists correctly.",
     "Designs list-driven features and keeps parallel lists consistent."))

CONCEPTS["myblocks"] = C(
    "My Blocks: your own blocks", "MyBlocks",
    ["define ()", "custom block"],
    ["Custom block — a block you invent yourself.",
     "Define — the script that says what your block does.",
     "Abstraction — hiding detail behind a simple name."],
    ["I can make a custom block.",
     "I can move repeated code into a custom block.",
     "I can explain why custom blocks make code clearer."],
    "Say: \"'Make a cup of tea' is one instruction, but it hides twelve steps. Your code can do that too.\" Abstraction in one sentence.",
    ["Find genuinely repeated code in their existing project — that authentic duplication is the motivation.",
     "Make a block named in plain English ('reset player', 'lose a life') and move the blocks into the define.",
     "Replace the duplicated stacks with the single new block. The script visibly shrinks — a powerful moment.",
     "Task: refactor a project so the main script reads like a set of instructions."],
    ["Child defines the block but never uses it → drag the new block into the script.",
     "Block named vaguely ('block1') → rename to describe what it does.",
     "Everything crammed into one custom block → one block, one job."],
    ["What is a custom block? → A block you make that runs your own script.",
     "Why use them? → Less repetition and clearer code.",
     "What is abstraction? → Hiding detail behind a simple name."],
    "Identify the repeated code for them; the child performs the move.",
    "Refactor an entire project into named blocks so the main script is readable end to end.",
    ("Creates a custom block with support.",
     "Moves repeated code into well-named custom blocks.",
     "Refactors projects for readability and explains abstraction."))

CONCEPTS["myblocks-params"] = C(
    "Custom blocks with inputs", "MyBlocks",
    ["define () with inputs", "custom block with number input"],
    ["Input (parameter) — a value you pass into your block.",
     "Argument — the actual value given when the block is used.",
     "Reuse — one block serving many situations."],
    ["I can add a number input to a custom block.",
     "I can use the input inside the definition.",
     "I can call the block with different values."],
    "Show two nearly identical custom blocks (`jump small`, `jump big`). Ask how to avoid writing both. One block with a number — done.",
    ["Add an input when creating the block; drag the orange parameter from the define hat into the blocks inside.",
     "Emphasise that the parameter is used INSIDE the definition — this is the step children miss.",
     "Call the block twice with different values and watch one definition serve both.",
     "Task: build `draw square (size)` or `damage (amount)` and use it several times."],
    ["Parameter not dragged in, so a fixed number is used → the block ignores its input; drag the orange oval in.",
     "Input named vaguely ('a') → name it 'size' or 'amount'.",
     "Child creates many similar blocks instead of one with an input → compare the two approaches."],
    ["What is a parameter? → A value passed into your block.",
     "Where do you use it? → Inside the define, dragged from the hat.",
     "Why is one block with an input better? → It works for every value."],
    "Provide the definition; the child only drags the parameter into place and calls it.",
    "Two parameters (size and colour) used together in a drawing block.",
    ("Uses a parameterised block made for them.",
     "Creates and correctly uses a block with an input.",
     "Designs reusable parameterised blocks with clear names."))

CONCEPTS["ask-answer"] = C(
    "Ask and answer: user input", "Sensing",
    ["ask () and wait", "answer", "join () ()"],
    ["Input — information the user types in.",
     "answer — the special block holding what the user typed.",
     "join — sticking two pieces of text together."],
    ["I can ask the user a question.",
     "I can use the answer in a response.",
     "I can store an answer in a variable."],
    "Ask: \"What makes a chatbot feel alive?\" It uses YOUR name back at you. That is `join` plus `answer`.",
    ["Demo `ask What is your name? and wait` then `say (answer)`. The project talks back — a genuinely delightful moment.",
     "Introduce `join Hello (answer)` for natural replies. Point out the space at the end of 'Hello '.",
     "Teach the critical trap: `answer` is overwritten by the NEXT ask. Store it: `set name to (answer)` immediately.",
     "Task: build a short conversation using two stored answers."],
    ["Second answer replaces the first → store each in its own variable right after asking.",
     "Reply reads 'HelloSam' → add a space inside the join text.",
     "Ask block used but never waited for → `ask and wait` is the correct block."],
    ["What holds what the user typed? → The `answer` block.",
     "Why store the answer in a variable? → The next ask overwrites it.",
     "How do you build a sentence? → With `join`."],
    "Give one ask and one say; the child changes the wording.",
    "Build a chatbot remembering three facts and using them later in the conversation.",
    ("Uses ask and answer with support.",
     "Stores answers in variables and builds joined replies.",
     "Designs a conversation using several stored inputs coherently."))

CONCEPTS["quiz-logic"] = C(
    "Quiz logic and answer checking", "Operators",
    ["ask () and wait", "answer", "() = ()", "if <> then else", "change () by ()"],
    ["Validation — checking whether an answer is correct.",
     "Case sensitivity — whether capital letters matter.",
     "Feedback — telling the user how they did."],
    ["I can check an answer against the correct one.",
     "I can score a quiz.",
     "I can give helpful feedback for right and wrong answers."],
    "Ask: \"If a quiz asks for 'Paris' and you type 'paris', should it be wrong?\" That debate IS the lesson.",
    ["Build `ask ... and wait` then `if <(answer) = Paris> then [change score by 1] else [say The answer was Paris]`.",
     "Test deliberately with wrong capitalisation. Scratch's `=` ignores case for letters — discuss why that is helpful here.",
     "Add the score and a final result message using a comparison.",
     "Task: build a 5-question quiz with scoring and a final grade."],
    ["Answer always marked wrong → an extra space, or comparing to the wrong variable.",
     "Score not reset → set it to 0 at the start.",
     "Only the last question scores → each question needs its own check."],
    ["How do you check an answer? → Compare `answer` with the correct value.",
     "Where do you add the point? → In the `then` branch.",
     "How do you grade at the end? → Compare the score with thresholds."],
    "Provide question one fully; the child copies the pattern for question two.",
    "Use lists so questions are random and never repeat, with a percentage score.",
    ("Checks one answer with support.",
     "Builds a multi-question quiz with scoring and feedback.",
     "Uses lists and randomisation for a robust quiz with grading."))

CONCEPTS["gravity"] = C(
    "Gravity and jumping", "Motion",
    ["change y by ()", "set () to ()", "change () by ()", "if <> then"],
    ["Velocity — speed and direction of movement.",
     "Gravity — a constant downward pull.",
     "Physics — modelling real movement with numbers."],
    ["I can model gravity with a velocity variable.",
     "I can make a sprite jump and fall naturally.",
     "I can tune values to change the feel."],
    "Drop a pen and ask: \"Did it fall at the same speed the whole way?\" No — it sped up. Real gravity accelerates, and so will their code.",
    ["Explain the two-variable pattern in plain words: velocity changes the position, gravity changes the velocity.",
     "Build it: `forever [change y by (velocity), change velocity by -1]`. Watch the sprite accelerate downward — that curve is real physics.",
     "Add jump: `set velocity to 12` on space. Add the ground check: `if <y position < -120> then [set y to -120, set velocity to 0]`.",
     "Tune together: gravity -1 versus -0.5, jump 12 versus 20. Feel is a design decision."],
    ["Sprite falls through the floor → the ground check is missing or the boundary is wrong.",
     "Jump is instant with no arc → velocity is being set every frame; set it once on the key press.",
     "Infinite jumping in mid-air → only allow a jump when on the ground."],
    ["What does the velocity variable do? → Controls how fast and which way the sprite moves vertically.",
     "What does gravity do to velocity? → Reduces it every frame.",
     "How do you stop mid-air jumping? → Check the sprite is on the ground first."],
    "Provide the gravity loop; the child adds only the jump and tunes numbers.",
    "Add double-jump, or variable jump height based on how long space is held.",
    ("Copies a gravity script.",
     "Builds working gravity and jumping with a ground check.",
     "Tunes physics for game feel and handles jump edge cases."))

CONCEPTS["platformer"] = C(
    "Platform collision", "Sensing",
    ["touching color ()?", "change y by ()", "change x by ()", "repeat until <>"],
    ["Platform — a surface the player can stand on.",
     "Collision resolution — pushing the player out of a wall.",
     "Hitbox — the area used for collision."],
    ["I can detect standing on a platform.",
     "I can stop the player passing through walls.",
     "I can build a simple platform level."],
    "Ask: \"In Mario, what stops you falling through the floor?\" The game checks, every frame, and pushes you back up.",
    ["Use one colour for all solid ground. Consistency makes collision reliable — a real design constraint.",
     "Teach the push-out pattern: `repeat until <not <touching color?>> [change y by 1]` — climb out of the ground rather than teleporting.",
     "Handle horizontal collision the same way so the player cannot walk through walls.",
     "Task: build a level with three platforms the player can traverse."],
    ["Player sinks into the ground → the push-out loop is missing.",
     "Player sticks to walls → separate the x and y collision checks.",
     "Collision unreliable → platform colours are slightly different shades; use one exact colour."],
    ["How does the game know you are standing on something? → Colour or sprite sensing below the player.",
     "What do you do when stuck inside a platform? → Move out one step at a time until free.",
     "Why use a single platform colour? → So one check works everywhere."],
    "Provide the collision blocks; the child designs the level layout.",
    "Add moving platforms or one-way platforms.",
    ("Detects platforms with support.",
     "Builds reliable platform collision for a playable level.",
     "Handles complex collision cases and designs balanced levels."))

CONCEPTS["pen"] = C(
    "Drawing with the pen", "Pen",
    ["pen down", "pen up", "erase all", "set pen color to ()", "set pen size to ()"],
    ["Pen — a tool letting a sprite draw as it moves.",
     "Trail — the line left behind.",
     "Canvas — the stage as a drawing surface."],
    ["I can make a sprite draw as it moves.",
     "I can control pen colour and size.",
     "I can clear the stage before drawing."],
    "Tie an imaginary pen to the sprite. \"Everything it does now leaves a trail — your sprite becomes a paintbrush.\"",
    ["Add the Pen extension together (children need to know extensions exist at the bottom-left).",
     "Demo `pen down` then movement. The trail appears — instantly engaging.",
     "Teach the essential habit: `erase all` and `pen up` at the start of every run, otherwise drawings pile up.",
     "Draw a square with `repeat 4 [move 100, turn 90]` — geometry and code together."],
    ["Stage covered in old drawings → `erase all` is missing at the start.",
     "Sprite draws when it should not → `pen up` before moving into position.",
     "Pen blocks missing → the Pen extension has not been added."],
    ["What does pen down do? → Makes the sprite draw as it moves.",
     "What should every pen project start with? → `erase all` and `pen up`.",
     "How do you draw a square? → Repeat 4 times: move then turn 90."],
    "Give the square code and let them change size and colour only.",
    "Draw a triangle and a hexagon — they must work out the turn angle (360 divided by the number of sides).",
    ("Draws with pen blocks provided.",
     "Controls the pen and draws shapes with loops, resetting properly.",
     "Derives angles for any polygon and composes multi-shape drawings."))

CONCEPTS["pen-art"] = C(
    "Geometric art and patterns", "Pen",
    ["repeat ()", "turn () degrees", "change pen color by ()", "set pen size to ()", "pick random () to ()"],
    ["Nested loop — a loop inside another loop.",
     "Pattern — a repeating design.",
     "Spirograph — art from repeated rotated shapes."],
    ["I can nest loops to create patterns.",
     "I can vary colour across a drawing.",
     "I can predict a pattern from its code."],
    "Show a spirograph image. \"Twelve lines of code made that. Let's find out how.\"",
    ["Build the nested loop: `repeat 36 [ repeat 4 [move 100, turn 90], turn 10 ]`. Square, rotate, repeat.",
     "Do the maths together: 36 x 10 = 360, a full circle. Children love that the numbers must agree.",
     "Add `change pen color by 5` inside the outer loop for a rainbow effect.",
     "Task: invent a pattern by changing the shape, the rotation and the repeat count."],
    ["Pattern does not close into a circle → repeats multiplied by the turn must equal 360.",
     "Drawing runs off-stage → reduce the move distance.",
     "Colour never changes → the change-pen-colour block is in the wrong loop."],
    ["Why 36 repeats and 10 degrees? → Together they make 360, a full circle.",
     "What does the inner loop draw? → One shape.",
     "How do you get a rainbow? → Change pen colour each time round the outer loop."],
    "Give the nested loop and let them change one number at a time, predicting each result.",
    "Ask them to design a pattern to a specification, then explain the maths behind it.",
    ("Runs a pattern script provided for them.",
     "Builds nested-loop patterns and varies colour deliberately.",
     "Designs original patterns and explains the underlying maths."))

CONCEPTS["music-blocks"] = C(
    "Making music with code", "Sound",
    ["play drum () for () beats", "play note () for () beats", "set tempo to ()", "rest for () beats"],
    ["Beat — the basic unit of musical time.",
     "Tempo — how fast the beats go.",
     "Note — a musical pitch, numbered in Scratch."],
    ["I can play notes and drums with code.",
     "I can build a rhythm with a loop.",
     "I can change tempo and hear the difference."],
    "Clap a beat and have the child join in. \"That pattern is a loop. We're going to write it down in code.\"",
    ["Add the Music extension. Demo `play drum 1 for 0.25 beats` inside a repeat to make a beat.",
     "Layer a second rhythm on another sprite so both play at once — the child hears parallel scripts working.",
     "Introduce notes (60 is middle C) and build a short melody. Numbers become music.",
     "Task: build a two-part piece — drums plus a melody — that starts together on the flag."],
    ["Parts drift out of sync → start both with the same broadcast rather than separate flag clicks.",
     "Music too fast or slow → adjust `set tempo`.",
     "Notes sound wrong → check the note numbers; 60 is middle C."],
    ["What is a beat? → The basic unit of musical time.",
     "How do you make two parts start together? → Trigger both with one broadcast.",
     "What does tempo change? → How fast it plays."],
    "Give a one-bar rhythm and let them repeat and vary it.",
    "Compose a piece with three layers and a structure (intro, verse, chorus).",
    ("Plays sounds with a script provided.",
     "Builds rhythms and melodies with loops and correct timing.",
     "Composes multi-part music synchronised with broadcasts."))

CONCEPTS["game-polish"] = C(
    "Polish and game feel", "Design",
    ["change () effect by ()", "start sound ()", "change size by ()", "broadcast ()"],
    ["Game feel — how satisfying a game is to play.",
     "Juice — small effects that make actions feel good.",
     "Playtest — watching someone else play to find problems."],
    ["I can add feedback to every player action.",
     "I can improve a game after watching someone play it.",
     "I can explain what makes a game feel good."],
    "Play the same action with and without sound, shake and pop. Ask which feels better. Polish is not decoration — it is communication.",
    ["List every player action in their game (move, collect, hit, win). Each one needs feedback: sound, animation or effect.",
     "Add a collect effect together: sound plus a quick grow-and-fade. Small work, large payoff.",
     "Playtest properly: the tutor plays while the CHILD watches silently and writes down every confusion. Not explaining is the hard part — and the lesson.",
     "Fix the top two issues found. Real iteration."],
    ["Child adds effects everywhere until it is chaotic → one clear effect per action.",
     "Child explains the game while it is being tested → the game must speak for itself.",
     "Feedback ignored because 'it's fine' → pick just the single most common confusion and fix that."],
    ["What is game feel? → How satisfying the game is to play.",
     "What did your playtester find confusing? → (child's own answer)",
     "Why watch silently? → Because a real player has nobody to explain it."],
    "Add feedback to one action together and let the child mirror it for the rest.",
    "Run two playtests and produce a prioritised fix list.",
    ("Adds effects when suggested.",
     "Gives every action clear feedback and acts on playtest findings.",
     "Iterates deliberately on feel and justifies design choices."))

CONCEPTS["publish-share"] = C(
    "Publishing and sharing", "Design",
    ["project notes", "share"],
    ["Publish — make a project visible to others.",
     "Instructions — telling a player how to play.",
     "Credits — acknowledging work you have used.",
     "Remix — building on someone else's shared project."],
    ["I can write clear instructions for my project.",
     "I can credit the work of others.",
     "I can share a project and respond to feedback."],
    "Ask: \"You open a game and there are no instructions. What do you do?\" Quit. Instructions are part of the game.",
    ["Write the Instructions field together: how to play in three lines, no jargon.",
     "Write Notes and Credits: what they made, what they reused, who helped. Attribution is an ethics lesson worth having early.",
     "Discuss online safety: no real names, no school, no personal details in a public project.",
     "Share the project and send the link to a parent — the moment the work becomes real."],
    ["Instructions assume the player already knows → test them on someone who has never seen the game.",
     "No credits for reused sprites or sounds → add them; it is good practice and good manners.",
     "Personal details in the project → remove them and explain why."],
    ["What three things do instructions need? → Goal, controls, how to win.",
     "Why credit others? → It is honest and respectful of their work.",
     "What should never go in a public project? → Personal details."],
    "Draft the instructions together sentence by sentence.",
    "Ask them to remix someone else's shared project and credit it properly.",
    ("Shares a project with prompting.",
     "Writes clear instructions and credits, and shares safely.",
     "Presents work professionally and uses feedback to improve it."))

CONCEPTS["l2-capstone"] = C(
    "Level 2 capstone project", "Design",
    ["all Level 2 blocks"],
    ["Specification — a written description of what will be built.",
     "Milestone — a checkpoint in a bigger build.",
     "Portfolio — a collection of work that shows your skill."],
    ["I can specify a multi-feature project.",
     "I can build it in stages, testing as I go.",
     "I can present my work and explain my code."],
    "Say: \"This is the project you'll show people. Make it something you'd actually want to play.\"",
    ["Write a one-page spec: title, goal, controls, three features, win and lose conditions. Agree it before any code.",
     "Break it into milestones and build one per session, testing each. Managing a build over time is the real Level 2 skill.",
     "Require at least three Level 2 techniques (clones, broadcasts, custom blocks, lists or physics).",
     "Finish with a presentation: demo, explain one clever piece of code, and say what was hardest and how they solved it."],
    ["Scope far too large → cut to three features; a finished game beats an ambitious unfinished one.",
     "Code becomes an unreadable tangle → refactor into custom blocks with clear names.",
     "Child stops testing near the end → test after every milestone, without exception."],
    ["What are your three features? → (child's own answer)",
     "Which milestone comes first and why? → Core mechanic first.",
     "Which Level 2 technique are you using and why? → (child's own answer)"],
    "Provide a spec template and co-plan the milestones.",
    "Add a stretch feature such as a level system, saved high scores or a boss.",
    ("Completes a guided project with support.",
     "Specifies, builds and tests a multi-feature project independently.",
     "Delivers an original polished project and explains their engineering decisions."))
