# -*- coding: utf-8 -*-
"""
curriculum.py — the exercise content, in the reference-platform model.

Sessions -> Exercises. Each exercise is a Mini Project, Home Task, or Recall
Test, with a difficulty, a concept tag, a themed set of REAL Scratch sprites, a
game template (its playable "desired output"), and instructions.
"""

# default step-by-step hints per game template
HINTS = {
 "collect": [
   "Move the player with the arrow keys.",
   "Make each gem vanish and add 1 to the score when the player touches it.",
   "Make the enemy chase the player (point towards it, then move).",
   "If the player touches the enemy, send it back to the start.",
   "When the score reaches 3, the goal sprite celebrates — You Win!",
   "Stretch: add lives, and a second area to explore."],
 "catch": [
   "Make the catcher follow the mouse along the bottom (set x to mouse x).",
   "Make the item fall — change y by a negative number, forever.",
   "If the item touches the catcher, add 1 to the score and send it back to the top.",
   "If the item drops off the bottom, lose a life and reset it.",
   "When lives reach 0, show Game Over.",
   "Stretch: make the item fall faster as your score climbs."],
 "dodge": [
   "Move the player with the arrow keys.",
   "Make each hazard fall from a random spot at the top.",
   "When a hazard passes the bottom, add 1 to the score and reset it.",
   "If a hazard touches the player, it's Game Over.",
   "Stretch: speed the hazards up the longer you survive."],
 "clicker": [
   "Add a score variable and set it to 0 at the start.",
   "When the target is clicked, add 1 to the score.",
   "Make the target pulse (change size, then back) so clicks feel good.",
   "When the score reaches the goal, celebrate — You Win!",
   "Stretch: add an upgrade that earns points automatically."],
 "quiz": [
   "Press the green flag to start the quiz.",
   "Read each question and type your answer, then press Enter.",
   "You earn a point for every correct answer.",
   "Your final score shows at the end.",
   "Stretch: try to score full marks!"],
 "flappy": [
   "Make the player fall — a 'gravity' variable that lowers its y a little every frame.",
   "When Space is pressed, give it an upward boost.",
   "Scroll the obstacle from right to left, forever.",
   "When the obstacle leaves the left edge, send it back to the right at a new height and score +1.",
   "If the player touches the obstacle or falls off the bottom, it's Game Over.",
   "Stretch: add a top and bottom obstacle with a gap to fly through."],
 "whack": [
   "Make the target pop up at a random spot, wait a moment, then hide — forever.",
   "When the target is clicked, add 1 to the score.",
   "Add a countdown timer that starts at 20.",
   "When the timer reaches 0, show the final score and stop the game.",
   "Stretch: make it pop up faster as the timer runs down."],
 "pong": [
   "Make the paddle follow your mouse along the bottom.",
   "Send the ball moving and bounce it off the walls (if on edge, bounce).",
   "When the ball hits the paddle, bounce it back up and score +1.",
   "If the ball drops below the paddle, it's Game Over.",
   "Stretch: speed the ball up a little on every hit."],
 "runner": [
   "Give the player gravity so it falls back to the ground.",
   "When Space is pressed (and it's on the ground), jump up.",
   "Scroll the obstacle from right to left, forever.",
   "Score +1 each time an obstacle passes; touching one is Game Over.",
   "Stretch: make the game speed up as your score rises."],
 "shooter": [
   "Move the ship left and right with the arrow keys.",
   "When Space is pressed, fire the bullet upward from the ship.",
   "Make the enemy fall from the top at a random spot.",
   "Hitting the enemy scores +1; the enemy reaching you is Game Over.",
   "Stretch: add lives, or more than one enemy."],
 "drive": [
   "Point the car, then move it forward with the up arrow.",
   "Turn left and right with the left/right arrows.",
   "Reach the finish flag to win.",
   "Touching another car sends you back to the start.",
   "Stretch: add a lap timer or more traffic."],
 "animation": [
   "Place your character on one side of the scene.",
   "Move it across with 'change x' (or 'glide') inside a loop.",
   "Switch costumes as it moves so it looks like it's walking or flying.",
   "Use 'say' to add a line of dialogue at the start and the end.",
   "Stretch: add a second character that reacts, or change the backdrop mid-scene."],
 "chatbot": [
   "Use 'ask and wait' to ask the player a question.",
   "The player's reply is stored in the 'answer' block.",
   "Use 'join' to reply using their answer (e.g. 'Nice to meet you, ___').",
   "Ask a few questions and give a friendly reply each time.",
   "Stretch: use 'if/else' to reply differently depending on the answer."],
 "art": [
   "Add the Pen extension, then 'erase all' and 'pen down'.",
   "Use a 'repeat' loop with 'move' and 'turn' to draw a pattern.",
   "Change the pen colour a little each step for a rainbow.",
   "Try different move amounts and turn angles for brand-new shapes.",
   "Stretch: make the pen follow the mouse so you can paint freely."],
 "music": [
   "Add the Music extension.",
   "Give each instrument a 'when this sprite clicked' script.",
   "Play a different drum on each instrument.",
   "Make it pulse (change size, then back) when clicked so it feels alive.",
   "Stretch: press the green flag to play a whole beat by itself."],
}

# colour per 'world' (used for the card thumbnail tile)
W = {"fantasy": "#7c3aed", "garden": "#16a34a", "space": "#2563eb",
     "food": "#f59e0b", "sea": "#0891b2", "review": "#e11d48"}


def mini(id, title, level, tag, emoji, color, template, theme, story):
    return {"id": id, "title": title, "type": "Mini Project", "level": level, "tag": tag,
            "emoji": emoji, "color": color, "template": template, "theme": theme,
            "story": story, "hints": HINTS[template]}

def home(id, title, level, tag, emoji, color, template, theme, story):
    d = mini(id, title, level, tag, emoji, color, template, theme, story)
    d["type"] = "Home Task"; return d

def recall(id, tag, color, questions, story):
    return {"id": id, "title": "Recall Test", "type": "Recall Test", "level": "Easy", "tag": tag,
            "emoji": "🧠", "color": W["review"], "template": "quiz",
            "theme": {"host": "Gobo", "backdrop": "Chalkboard", "questions": questions},
            "story": story, "hints": HINTS["quiz"]}


SESSIONS = [
 {"id": "S1", "n": 1, "title": "Gem Hunt", "emoji": "💎", "color": W["fantasy"],
  "concept": "Move a sprite with the arrow keys and detect when it touches things.",
  "exercises": [
    mini("S1E1", "Gem Hunt", "Easy", "Movement & collision", "💎", W["fantasy"], "collect",
         {"player": "Wizard", "collectible": "Crystal", "enemy": "Ghost", "goal": "Dragon", "backdrop": "Castle 3",
          "win": "You collected all 3 crystals — YOU WIN!"},
         "A young wizard is trapped in a castle. Collect the three magic crystals, dodge the ghost, and reach the dragon to break the spell."),
    home("S1E2", "Home Task — Haunted Halls", "Easy", "Movement & collision", "👻", W["fantasy"], "collect",
         {"player": "Witch", "collectible": "Star", "enemy": "Ghost", "goal": "Griffin", "backdrop": "Woods",
          "win": "All 3 stars collected — the griffin is free!"},
         "A witch must gather three fallen stars in the haunted woods while a ghost gives chase, then reach the griffin."),
    recall("S1E3", "Movement & collision", W["review"],
           [("Which blocks move a sprite left and right?", "change x"),
            ("What block checks if two sprites touch?", "touching"),
            ("A block that repeats forever is called a ___?", "forever")],
           "Recall what you learned about moving sprites and detecting touches.")]},

 {"id": "S2", "n": 2, "title": "Apple Catch", "emoji": "🍎", "color": W["garden"],
  "concept": "Use coordinates and a score variable to catch falling objects.",
  "exercises": [
    mini("S2E1", "Apple Catch", "Easy", "Coordinates & score", "🍎", W["garden"], "catch",
         {"player": "Bowl", "item": "Apple", "backdrop": "Blue Sky"},
         "Apples are falling from the trees! Move the bowl with your mouse and catch as many as you can before you run out of lives."),
    home("S2E2", "Home Task — Banana Bonanza", "Easy", "Coordinates & score", "🍌", W["garden"], "catch",
         {"player": "Bowl", "item": "Bananas", "backdrop": "Beach Rio"},
         "The monkeys are dropping bananas on the beach. Catch them in your bowl!"),
    recall("S2E3", "Coordinates & score", W["review"],
           [("Which value goes left-right on the stage, x or y?", "x"),
            ("What do we call a labelled box that stores a number?", "variable"),
            ("Which block makes a sprite follow the mouse?", "set x to mouse x")],
           "Recall coordinates and how a score variable works.")]},

 {"id": "S3", "n": 3, "title": "Asteroid Dodge", "emoji": "☄️", "color": W["space"],
  "concept": "Use loops and if-blocks to dodge falling hazards.",
  "exercises": [
    mini("S3E1", "Asteroid Dodge", "Medium", "Loops & conditionals", "☄️", W["space"], "dodge",
         {"player": "Rocketship", "enemy": "Rocks", "backdrop": "Space"},
         "Pilot your rocket through an asteroid field. Dodge the falling rocks and survive as long as you can!"),
    home("S3E2", "Home Task — Meteor Storm", "Medium", "Loops & conditionals", "🤖", W["space"], "dodge",
         {"player": "Robot", "enemy": "Rocks", "backdrop": "Nebula"},
         "A robot explorer is caught in a meteor storm inside a glowing nebula. Keep it safe!"),
    recall("S3E3", "Loops & conditionals", W["review"],
           [("A block that runs code only when something is true is an ___ block?", "if"),
            ("What do we call code that repeats?", "loop"),
            ("Which block picks a random number?", "pick random")],
           "Recall loops and conditionals.")]},

 {"id": "S4", "n": 4, "title": "Donut Clicker", "emoji": "🍩", "color": W["food"],
  "concept": "Use variables and events to build a clicker game.",
  "exercises": [
    mini("S4E1", "Donut Clicker", "Easy", "Variables & events", "🍩", W["food"], "clicker",
         {"target": "Donut", "backdrop": "Party"},
         "Click the donut as fast as you can! Every click adds to your score — reach 25 to win the party."),
    home("S4E2", "Home Task — Star Tapper", "Easy", "Variables & events", "⭐", W["space"], "clicker",
         {"target": "Star", "backdrop": "Galaxy"},
         "Tap the shooting star across the galaxy to light up the sky."),
    recall("S4E3", "Variables & events", W["review"],
           [("Which block runs when you click a sprite? when this sprite ___?", "clicked"),
            ("Which block adds to a variable?", "change score by"),
            ("What starts every script when the flag is pressed? when green flag ___?", "clicked")],
           "Recall variables and events.")]},

 {"id": "S5", "n": 5, "title": "Deep Dive Dodge", "emoji": "🐟", "color": W["sea"],
  "concept": "Sensing and touching in an underwater world.",
  "exercises": [
    mini("S5E1", "Deep Dive Dodge", "Medium", "Sensing & touching", "🐟", W["sea"], "dodge",
         {"player": "Fish", "enemy": "Jellyfish", "backdrop": "Underwater 1"},
         "Swim your little fish through a swarm of drifting jellyfish. Don't get stung!"),
    home("S5E2", "Home Task — Urchin Alley", "Medium", "Sensing & touching", "🦑", W["sea"], "dodge",
         {"player": "Fish", "enemy": "Pufferfish", "backdrop": "Underwater 2"},
         "Pufferfish are drifting down through the reef. Guide your fish safely past them."),
    recall("S5E3", "Sensing & touching", W["review"],
           [("Which category has the touching block? (colour is light blue)", "sensing"),
            ("Which block reports how far one sprite is from another?", "distance to"),
            ("touching [sprite]? reports true or ___?", "false")],
           "Recall sensing and touching.")]},

 {"id": "S6", "n": 6, "title": "Treasure Reef", "emoji": "🐚", "color": W["sea"],
  "concept": "Combine movement, collecting, and a win condition.",
  "exercises": [
    mini("S6E1", "Treasure Reef", "Medium", "Score & win condition", "🐚", W["sea"], "collect",
         {"player": "Diver1", "collectible": "Starfish", "enemy": "Shark 2", "goal": "Octopus", "backdrop": "Underwater 2",
          "win": "All 3 starfish found — the octopus is delighted!"},
         "Dive the reef to gather three glowing starfish, keep clear of the shark, and reach the friendly octopus."),
    home("S6E2", "Home Task — Crab Cove", "Medium", "Score & win condition", "🦀", W["sea"], "collect",
         {"player": "Crab", "collectible": "Crystal", "enemy": "Shark 2", "goal": "Octopus", "backdrop": "Underwater 1",
          "win": "3 crystals collected — you win!"},
         "A brave crab scuttles the cove for crystals while dodging the shark."),
    recall("S6E3", "Score & win condition", W["review"],
           [("What should you set the score to at the very start?", "0"),
            ("Which block ends the game? stop ___?", "all"),
            ("A message you send to all sprites at once is a ___?", "broadcast")],
           "Recall scoring and win conditions.")]},

 {"id": "S7", "n": 7, "title": "Fruit Frenzy", "emoji": "🍉", "color": W["food"],
  "concept": "Lives and game-over screens.",
  "exercises": [
    mini("S7E1", "Fruit Frenzy", "Medium", "Lives & game over", "🍉", W["food"], "catch",
         {"player": "Bowl", "item": "Watermelon", "backdrop": "Farm"},
         "Watermelons are rolling off the farm cart! Catch them — but miss three and it's game over."),
    home("S7E2", "Home Task — Cake Catch", "Medium", "Lives & game over", "🎂", W["food"], "catch",
         {"player": "Bowl", "item": "Cake", "backdrop": "Bedroom 1"},
         "Slices of cake are tumbling down. Catch them before they hit the floor!"),
    recall("S7E3", "Lives & game over", W["review"],
           [("What do we call the tries a player has before the game ends?", "lives"),
            ("Which block subtracts one from lives?", "change lives by -1"),
            ("When lives = 0 we usually show a ___ screen?", "game over")],
           "Recall lives and game over.")]},

 {"id": "S8", "n": 8, "title": "Dragon's Keep (Capstone)", "emoji": "🐉", "color": W["fantasy"],
  "concept": "Put it all together into a bigger adventure.",
  "exercises": [
    mini("S8E1", "Dragon's Keep", "Hard", "Capstone project", "🐉", W["fantasy"], "collect",
         {"player": "Wizard", "collectible": "Crystal", "enemy": "Ghost", "goal": "Dragon", "backdrop": "Castle 1",
          "win": "You freed the dragon — YOU WIN!"},
         "The final challenge. A wizard braves the great keep to collect the crystals, outwit the ghost, and awaken the dragon."),
    home("S8E2", "Home Task — Knight's Quest", "Hard", "Capstone project", "🛡️", W["fantasy"], "collect",
         {"player": "Knight", "collectible": "Crystal", "enemy": "Ghost", "goal": "Dragon", "backdrop": "Castle 2",
          "win": "The knight collected all 3 crystals — victory!"},
         "A knight takes on the same keep. Can you beat it a second way?"),
    recall("S8E3", "Final review", W["review"],
           [("Name the block that repeats code forever.", "forever"),
            ("Name the block that makes a decision.", "if"),
            ("Name the block that stores a number you can change.", "variable")],
           "A final review of everything in this level.")]},

 {"id": "S9", "n": 9, "title": "Flappy Flight", "emoji": "🦜", "color": W["garden"],
  "concept": "Gravity and a flap: fly through gaps with a falling-and-boosting sprite.",
  "exercises": [
    mini("S9E1", "Flappy Parrot", "Medium", "Gravity & flap", "🦜", W["garden"], "flappy",
         {"player": "Parrot", "obstacle": "Tree1", "backdrop": "Jungle"},
         "Tap Space to keep the parrot in the air and flap through the trees. How far can you fly?"),
    home("S9E2", "Home Task — Bat Flight", "Medium", "Gravity & flap", "🦇", W["fantasy"], "flappy",
         {"player": "Bat", "obstacle": "Rocks", "backdrop": "Woods"},
         "A little bat flutters through a rocky cave at dusk. Don't hit the rocks!"),
    recall("S9E3", "Gravity & flap", W["review"],
           [("What pulls a sprite down every frame?", "gravity"),
            ("Which key gives the flap boost in our game?", "space"),
            ("A value that goes up and down like speed is a ___?", "variable")],
           "Recall gravity and the flap boost.")]},

 {"id": "S10", "n": 10, "title": "Whack Attack", "emoji": "🔨", "color": W["food"],
  "concept": "Random positions and a countdown timer.",
  "exercises": [
    mini("S10E1", "Whack-a-Mouse", "Easy", "Random & timing", "🐭", W["food"], "whack",
         {"target": "Mouse1", "backdrop": "Farm"},
         "Mice keep popping out of the barn! Click them as fast as you can before the timer runs out."),
    home("S10E2", "Home Task — Bug Bash", "Easy", "Random & timing", "🐞", W["garden"], "whack",
         {"target": "Beetle", "backdrop": "Garden-rock"},
         "Beetles are popping up all over the garden. Bash as many as you can in 20 seconds!"),
    recall("S10E3", "Random & timing", W["review"],
           [("Which block picks a spot you can't predict? pick ___?", "random"),
            ("Which block pauses the script? wait ___ seconds?", "1"),
            ("What counts down to end the game?", "timer")],
           "Recall random positions and timing.")]},

 {"id": "S11", "n": 11, "title": "Galaxy Gems", "emoji": "🌟", "color": W["space"],
  "concept": "Collecting and scoring, out in space.",
  "exercises": [
    mini("S11E1", "Galaxy Gems", "Medium", "Score & collecting", "🌟", W["space"], "collect",
         {"player": "Robot", "collectible": "Star", "enemy": "Ghost", "goal": "Planet2", "backdrop": "Stars",
          "win": "All 3 stars collected — the planet is yours!"},
         "Pilot a robot through the stars, gather three of them, dodge the space ghost, and reach the planet."),
    home("S11E2", "Home Task — Moon Run", "Medium", "Score & collecting", "🌙", W["space"], "collect",
         {"player": "Retro Robot", "collectible": "Star", "enemy": "Ghost", "goal": "Earth", "backdrop": "Moon",
          "win": "3 stars collected — head home to Earth!"},
         "A retro robot hops across the moon collecting stars on the way back to Earth."),
    recall("S11E3", "Score & collecting", W["review"],
           [("What should the score be set to at the start?", "0"),
            ("Which block adds one to the score?", "change score by 1"),
            ("Which block hides a collected item?", "hide")],
           "Recall scoring and collecting.")]},

 {"id": "S12", "n": 12, "title": "Jungle Dash", "emoji": "🐒", "color": W["garden"],
  "concept": "Dodging falling hazards with loops and if-blocks.",
  "exercises": [
    mini("S12E1", "Jungle Dash", "Medium", "Loops & conditionals", "🐒", W["garden"], "dodge",
         {"player": "Monkey", "enemy": "Rocks", "backdrop": "Jungle"},
         "Coconuts are raining down in the jungle! Move the monkey to dodge them and survive."),
    home("S12E2", "Home Task — Desert Dash", "Medium", "Loops & conditionals", "🐍", W["food"], "dodge",
         {"player": "Snake", "enemy": "Rocks", "backdrop": "Desert"},
         "A snake slithers through a rockslide in the desert. Keep it safe!"),
    recall("S12E3", "Loops & conditionals", W["review"],
           [("Code that repeats is a ___?", "loop"),
            ("A block that checks something is true is an ___ block?", "if"),
            ("Which block makes something happen from a random edge? pick ___?", "random")],
           "Recall loops and conditionals.")]},

 {"id": "S13", "n": 13, "title": "Pet Clicker", "emoji": "🐶", "color": W["food"],
  "concept": "More variables and events, with a friendly pet.",
  "exercises": [
    mini("S13E1", "Puppy Clicker", "Easy", "Variables & events", "🐶", W["food"], "clicker",
         {"target": "Puppy", "backdrop": "Bedroom 1"},
         "Click the happy puppy to give it treats — reach 25 to make it the happiest pup ever!"),
    home("S13E2", "Home Task — Kitty Clicker", "Easy", "Variables & events", "🐱", W["fantasy"], "clicker",
         {"target": "Cat 2", "backdrop": "Room 1"},
         "Pet the kitty by clicking it. Can you reach the goal?"),
    recall("S13E3", "Variables & events", W["review"],
           [("Which block runs on a click? when this sprite ___?", "clicked"),
            ("Which block makes a sprite bigger for feedback? change ___ by?", "size"),
            ("A labelled box that stores your clicks is a ___?", "variable")],
           "Recall variables and events.")]},

 {"id": "S14", "n": 14, "title": "Berry Catch", "emoji": "🍓", "color": W["garden"],
  "concept": "Catching, scoring, and lives — again, with new fruit.",
  "exercises": [
    mini("S14E1", "Berry Catch", "Medium", "Score & lives", "🍓", W["garden"], "catch",
         {"player": "Bowl", "item": "Strawberry", "backdrop": "Hay Field"},
         "Strawberries are dropping from the vines. Catch them in your bowl — miss three and it's over."),
    home("S14E2", "Home Task — Orange Drop", "Medium", "Score & lives", "🍊", W["food"], "catch",
         {"player": "Bowl", "item": "Orange", "backdrop": "Farm"},
         "Oranges are rolling off the farm stand. Don't let them hit the ground!"),
    recall("S14E3", "Score & lives", W["review"],
           [("What do we call the tries before game over?", "lives"),
            ("Which value is left-right on the stage?", "x"),
            ("Which block follows the mouse? set x to mouse ___?", "x")],
           "Recall scoring, coordinates and lives.")]},

 {"id": "S15", "n": 15, "title": "Rocket Rush", "emoji": "🚀", "color": W["space"],
  "concept": "Gravity and flap in space — tune the feel.",
  "exercises": [
    mini("S15E1", "Rocket Rush", "Hard", "Game feel", "🚀", W["space"], "flappy",
         {"player": "Rocketship", "obstacle": "Planet2", "backdrop": "Nebula"},
         "Thread your rocket through the planets. Tap Space to fire the thrusters and don't crash!"),
    home("S15E2", "Home Task — UFO Flight", "Hard", "Game feel", "🛸", W["space"], "flappy",
         {"player": "Retro Robot", "obstacle": "Rocks", "backdrop": "Galaxy"},
         "Fly the little robot's saucer through an asteroid gauntlet across the galaxy."),
    recall("S15E3", "Game feel", W["review"],
           [("Making a game feel good is called game ___?", "feel"),
            ("Numbers you adjust to tune a game are ___?", "variables"),
            ("Which block gives the upward boost? change ___ by?", "y")],
           "Recall tuning and game feel.")]},

 {"id": "S16", "n": 16, "title": "Ocean Whack", "emoji": "🦀", "color": W["sea"],
  "concept": "Random pop-ups and timing, under the sea.",
  "exercises": [
    mini("S16E1", "Crab Whack", "Medium", "Random & timing", "🦀", W["sea"], "whack",
         {"target": "Crab", "backdrop": "Underwater 1"},
         "Crabs keep scuttling out from the sand! Tap them fast before the timer runs out."),
    home("S16E2", "Home Task — Jelly Tap", "Medium", "Random & timing", "🎐", W["sea"], "whack",
         {"target": "Jellyfish", "backdrop": "Underwater 2"},
         "Glowing jellyfish drift up from the deep. Tap as many as you can!"),
    recall("S16E3", "Final review", W["review"],
           [("Name a block that repeats forever.", "forever"),
            ("Name the block that stores a changing number.", "variable"),
            ("Name the block that reacts to a click.", "when this sprite clicked")],
           "A final review across all the games.")]},

 {"id": "S17", "n": 17, "title": "Neon Pong", "emoji": "🏓", "color": W["space"],
  "concept": "Bouncing a ball off walls and a paddle.",
  "exercises": [
    mini("S17E1", "Neon Pong", "Medium", "Bouncing & angles", "🏓", W["space"], "pong",
         {"paddle": "Paddle", "ball": "Ball", "backdrop": "Neon Tunnel"},
         "Keep the glowing ball in play! Slide the paddle with your mouse and bounce it back — don't let it drop."),
    home("S17E2", "Home Task — Beach Bounce", "Medium", "Bouncing & angles", "🏖️", W["sea"], "pong",
         {"paddle": "Paddle", "ball": "Beachball", "backdrop": "Beach Malibu"},
         "A beach ball is bouncing on the shore. Keep it up with your paddle!"),
    recall("S17E3", "Bouncing & angles", W["review"],
           [("Which block bounces a sprite off the walls? if on edge, ___?", "bounce"),
            ("A direction is measured in ___?", "degrees"),
            ("Which block sets which way a sprite faces? point in ___?", "direction")],
           "Recall bouncing and directions.")]},

 {"id": "S18", "n": 18, "title": "City Runner", "emoji": "🏃", "color": W["food"],
  "concept": "Jump over scrolling obstacles with gravity.",
  "exercises": [
    mini("S18E1", "City Runner", "Medium", "Jump & gravity", "🏃", W["food"], "runner",
         {"player": "Cat 2", "obstacle": "Rocks", "backdrop": "Metro"},
         "Run through the city and jump the obstacles! Tap Space to leap over each one."),
    home("S18E2", "Home Task — Dino Run", "Medium", "Jump & gravity", "🦖", W["garden"], "runner",
         {"player": "Dinosaur4", "obstacle": "Rocks", "backdrop": "Jurassic"},
         "A dino dashes across prehistoric plains — jump the rocks to survive!"),
    recall("S18E3", "Jump & gravity", W["review"],
           [("What pulls the runner back to the ground?", "gravity"),
            ("Which key makes it jump in our game?", "space"),
            ("Code that repeats is a ___?", "loop")],
           "Recall jumping and gravity.")]},

 {"id": "S19", "n": 19, "title": "Space Blaster", "emoji": "🔫", "color": W["space"],
  "concept": "Shoot bullets and score by hitting enemies.",
  "exercises": [
    mini("S19E1", "Space Blaster", "Hard", "Shooting & scoring", "🔫", W["space"], "shooter",
         {"player": "Rocketship", "bullet": "Ball", "enemy": "Ghost", "backdrop": "Space"},
         "Defend the galaxy! Move with the arrows and press Space to blast the space ghosts."),
    home("S19E2", "Home Task — Alien Attack", "Hard", "Shooting & scoring", "👾", W["space"], "shooter",
         {"player": "Rocketship", "bullet": "Star", "enemy": "Ghost", "backdrop": "Nebula"},
         "Aliens are swarming the nebula. Fire your star-blaster and hold the line!"),
    recall("S19E3", "Shooting & scoring", W["review"],
           [("Which key fires the bullet in our game?", "space"),
            ("Which block checks if the bullet hit the enemy? touching ___?", "enemy"),
            ("Which block sends the bullet up? change ___ by?", "y")],
           "Recall shooting and scoring.")]},

 {"id": "S20", "n": 20, "title": "City Speedway", "emoji": "🏎️", "color": W["review"],
  "concept": "Steer a car and reach the finish line.",
  "exercises": [
    mini("S20E1", "City Speedway", "Medium", "Steering & finish", "🏎️", W["space"], "drive",
         {"player": "Convertible", "goal": "Green Flag", "enemy": "Convertible 2", "backdrop": "Night City"},
         "Drive through the night city to the finish flag — steer with the arrows and dodge the other car!"),
    home("S20E2", "Home Task — Truck Trail", "Medium", "Steering & finish", "🚚", W["food"], "drive",
         {"player": "Truck", "goal": "Green Flag", "enemy": "City Bus", "backdrop": "Metro"},
         "Haul your truck across town to the finish, avoiding the bus."),
    recall("S20E3", "Steering & finish", W["review"],
           [("Which blocks rotate a sprite? turn left / turn ___?", "right"),
            ("Which block moves the car forward?", "move"),
            ("Which block checks you reached the flag? ___ Green Flag?", "touching")],
           "Recall steering and reaching a goal.")]},

 {"id": "S21", "n": 21, "title": "Sport Bounce", "emoji": "⚽", "color": W["garden"],
  "concept": "More bounce games with sports balls.",
  "exercises": [
    mini("S21E1", "Soccer Bounce", "Medium", "Bounce reinforce", "⚽", W["garden"], "pong",
         {"paddle": "Paddle", "ball": "Soccer Ball", "backdrop": "Playing Field"},
         "Keep the soccer ball in the air with your paddle. How long can you keep the streak?"),
    home("S21E2", "Home Task — Basket Bounce", "Medium", "Bounce reinforce", "🏀", W["food"], "pong",
         {"paddle": "Paddle", "ball": "Basketball", "backdrop": "Basketball 1"},
         "Bounce the basketball off your paddle and rack up points."),
    recall("S21E3", "Bounce reinforce", W["review"],
           [("Which block keeps the paddle on the mouse? set x to mouse ___?", "x"),
            ("What ends the game when the ball drops? stop ___?", "all"),
            ("Which block bounces off walls? if on edge, ___?", "bounce")],
           "Recall the bounce game.")]},

 {"id": "S22", "n": 22, "title": "Wild Run", "emoji": "🐆", "color": W["garden"],
  "concept": "More running and jumping.",
  "exercises": [
    mini("S22E1", "Monkey Run", "Medium", "Run reinforce", "🐒", W["garden"], "runner",
         {"player": "Monkey", "obstacle": "Tree1", "backdrop": "Jungle"},
         "Swing into action — run through the jungle and jump the logs!"),
    home("S22E2", "Home Task — Fox Dash", "Medium", "Run reinforce", "🦊", W["fantasy"], "runner",
         {"player": "Fox", "obstacle": "Rocks", "backdrop": "Forest"},
         "A quick fox dashes through the forest. Time your jumps!"),
    recall("S22E3", "Run reinforce", W["review"],
           [("Which key makes the runner jump?", "space"),
            ("Which variable stores the jump speed?", "vy"),
            ("What pulls it down each frame?", "gravity")],
           "Recall the runner game.")]},

 {"id": "S23", "n": 23, "title": "Sky Defender", "emoji": "🚀", "color": W["space"],
  "concept": "More shooting practice.",
  "exercises": [
    mini("S23E1", "Sky Defender", "Hard", "Shooter reinforce", "🚀", W["space"], "shooter",
         {"player": "Rocketship", "bullet": "Ball", "enemy": "Bat", "backdrop": "Galaxy"},
         "Bats are diving from the galaxy's edge! Blast them before they reach your ship."),
    home("S23E2", "Home Task — Bug Blaster", "Hard", "Shooter reinforce", "🐞", W["garden"], "shooter",
         {"player": "Rocketship", "bullet": "Star", "enemy": "Beetle", "backdrop": "Nebula"},
         "Space bugs incoming — fire your star-blaster and keep scoring!"),
    recall("S23E3", "Shooter reinforce", W["review"],
           [("Which block moves the bullet to the ship? go to ___?", "ship"),
            ("Which block waits for the fire key? wait ___?", "until"),
            ("Which block adds to the score?", "change score by 1")],
           "Recall the shooter game.")]},

 {"id": "S24", "n": 24, "title": "Grand Prix", "emoji": "🏁", "color": W["review"],
  "concept": "The final driving challenge.",
  "exercises": [
    mini("S24E1", "Moto Race", "Medium", "Driving reinforce", "🏍️", W["space"], "drive",
         {"player": "Motorcycle", "goal": "Green Flag", "enemy": "Convertible", "backdrop": "Colorful City"},
         "Weave your motorbike through traffic to the chequered flag!"),
    home("S24E2", "Home Task — Bus Dash", "Medium", "Driving reinforce", "🚌", W["food"], "drive",
         {"player": "City Bus", "goal": "Green Flag", "enemy": "Convertible 2", "backdrop": "Urban"},
         "Drive the city bus on its route to the finish, dodging traffic."),
    recall("S24E3", "Grand finale review", W["review"],
           [("Name a block that turns a sprite.", "turn right"),
            ("Name a block that repeats forever.", "forever"),
            ("Name a block that stores a score.", "variable")],
           "The grand finale review across every game type!")]},

 # ---------- Beyond games: animation, music, art, chatbots, stories ----------
 {"id": "S25", "n": 25, "title": "Lost in Space", "emoji": "🚀", "color": W["space"],
  "concept": "Make an animation: sequence movement, costumes and dialogue.",
  "exercises": [
    mini("S25E1", "Lost in Space", "Easy", "Animation & sequencing", "🚀", W["space"], "animation",
         {"mover": "Rocketship", "scenery": "Planet2", "backdrop": "Stars",
          "line1": "3… 2… 1… blast off!", "line2": "A whole new world!"},
         "Program your own animation: a little rocket drifts through the stars towards a distant planet, narrating its journey."),
    home("S25E2", "Home Task — Catch the Bus", "Easy", "Animation & sequencing", "🚌", W["food"], "animation",
         {"mover": "Cat 2", "scenery": "City Bus", "backdrop": "Metro",
          "line1": "Wait for me!", "line2": "Phew — just made it!"},
         "Animate a character hurrying across town to catch the bus before it leaves."),
    recall("S25E3", "Animation & sequencing", W["review"],
           [("Switching pictures to make movement uses ___?", "costumes"),
            ("Which block moves a sprite smoothly over time?", "glide"),
            ("Doing steps in order is called a ___?", "sequence")],
           "Recall animation and sequencing.")]},

 {"id": "S26", "n": 26, "title": "Dance Party", "emoji": "🕺", "color": W["review"],
  "concept": "Loop costumes to a beat to make sprites dance.",
  "exercises": [
    mini("S26E1", "Dance Party", "Easy", "Costumes & loops", "🕺", W["review"], "animation",
         {"mover": "Cassy Dance", "scenery": "Speaker", "backdrop": "Spotlight", "my": -20,
          "line1": "Let's dance!", "line2": "Great moves!"},
         "Throw a dance party! Loop the dancer's costumes so it grooves across the stage to the beat."),
    home("S26E2", "Home Task — Star Performer", "Easy", "Costumes & loops", "🎤", W["fantasy"], "animation",
         {"mover": "Ten80 Dance", "scenery": "Microphone", "backdrop": "Concert", "my": -20,
          "line1": "Take the stage!", "line2": "Encore!"},
         "Put a performer centre-stage and animate a show-stopping routine."),
    recall("S26E3", "Costumes & loops", W["review"],
           [("Which block moves to the next picture?", "next costume"),
            ("Which block repeats the dance forever?", "forever"),
            ("Which block adds a pause between moves? wait ___ seconds?", "1")],
           "Recall costumes and loops.")]},

 {"id": "S27", "n": 27, "title": "Rock Band", "emoji": "🥁", "color": W["food"],
  "concept": "Make musical instruments you play by clicking.",
  "exercises": [
    mini("S27E1", "Rock Band", "Easy", "Sound & events", "🥁", W["food"], "music",
         {"pads": [("Drum", 2, -140, -30), ("Drums Conga", 14, -45, -30), ("Drum-cymbal", 4, 45, -30), ("Drum-snare", 1, 140, -30)],
          "backdrop": "Concert"},
         "Build a band you can play! Click each instrument to hit a drum and jam out your own rhythm."),
    home("S27E2", "Home Task — Drum Kit", "Easy", "Sound & events", "🥁", W["review"], "music",
         {"pads": [("Drum-snare", 1, -140, -30), ("Drum-highhat", 6, -45, -30), ("Drum-cymbal", 4, 45, -30), ("Drums Tabla", 13, 140, -30)],
          "backdrop": "Bedroom 2"},
         "Set up a full drum kit and tap out a beat by clicking each drum."),
    recall("S27E3", "Sound & events", W["review"],
           [("Which block runs when you click a sprite? when this sprite ___?", "clicked"),
            ("Which extension adds drums and notes?", "music"),
            ("Making a sprite bigger for a moment uses change ___?", "size")],
           "Recall sound and events.")]},

 {"id": "S28", "n": 28, "title": "Flower Generator", "emoji": "🌸", "color": W["garden"],
  "concept": "Draw amazing patterns with the Pen and loops.",
  "exercises": [
    mini("S28E1", "Spirograph", "Medium", "Pen & patterns", "🌀", W["space"], "art",
         {"pen": "Ball", "backdrop": "Stars", "color": "#33d1ff", "points": 72, "arm": 120, "angle": 175},
         "Turn code into art! A hidden pen draws a hypnotic rainbow spirograph. Change the numbers to invent new patterns."),
    home("S28E2", "Home Task — Star Burst", "Medium", "Pen & patterns", "✨", W["fantasy"], "art",
         {"pen": "Ball", "backdrop": "Rays", "color": "#ffd21a", "points": 50, "arm": 150, "angle": 144},
         "Draw a dazzling burst of stars by repeating a shape and turning a little each time."),
    recall("S28E3", "Pen & patterns", W["review"],
           [("Which extension lets a sprite draw?", "pen"),
            ("Which pen block starts drawing? pen ___?", "down"),
            ("Which block repeats the drawing steps?", "repeat")],
           "Recall the Pen and patterns.")]},

 {"id": "S29", "n": 29, "title": "Chatbot", "emoji": "🤖", "color": W["space"],
  "concept": "Ask questions and reply using the player's answers.",
  "exercises": [
    mini("S29E1", "Chatbot", "Easy", "Ask & answer", "🤖", W["space"], "chatbot",
         {"bot": "Gobo", "backdrop": "Colorful City", "name": "Gobo"},
         "Build a friendly robot that asks your name and questions, then chats back using your answers."),
    home("S29E2", "Home Task — Fortune Teller", "Easy", "Ask & answer", "🔮", W["fantasy"], "chatbot",
         {"bot": "Wizard", "backdrop": "Witch House", "name": "Zara"},
         "Make a mystical fortune teller that asks about you and gives a fun reply."),
    recall("S29E3", "Ask & answer", W["review"],
           [("Which block asks the player to type something? ask and ___?", "wait"),
            ("Where is the player's reply stored?", "answer"),
            ("Which block sticks two pieces of text together?", "join")],
           "Recall asking and answering.")]},

 {"id": "S30", "n": 30, "title": "Story Time", "emoji": "📖", "color": W["fantasy"],
  "concept": "Tell a story with characters, movement and dialogue.",
  "exercises": [
    mini("S30E1", "The Quest", "Medium", "Storytelling", "🐉", W["fantasy"], "animation",
         {"mover": "Prince", "scenery": "Dragon", "backdrop": "Castle 4", "my": -30,
          "line1": "I must reach the castle…", "line2": "At last — the dragon!"},
         "Tell a mini adventure: a hero journeys across the land toward a waiting dragon, narrating the tale."),
    home("S30E2", "Home Task — Under the Sea", "Medium", "Storytelling", "🧜", W["sea"], "animation",
         {"mover": "Mermaid", "scenery": "Octopus", "backdrop": "Underwater 2", "my": -20,
          "line1": "Let's explore the reef!", "line2": "Hello, friend!"},
         "Write an underwater story where a mermaid swims out to meet a friendly octopus."),
    recall("S30E3", "Storytelling", W["review"],
           [("Sending a message to start the next part is a ___?", "broadcast"),
            ("Changing the scene uses switch ___?", "backdrop"),
            ("Two characters talking take turns using ___ blocks?", "say")],
           "Recall storytelling in Scratch.")]},
]
